// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gwresult.proto

package gwresult

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FlowProtos int32

const (
	FlowProtos_FP_UNKNOWN FlowProtos = 0
)

var FlowProtos_name = map[int32]string{
	0: "FP_UNKNOWN",
}

var FlowProtos_value = map[string]int32{
	"FP_UNKNOWN": 0,
}

func (x FlowProtos) String() string {
	return proto.EnumName(FlowProtos_name, int32(x))
}

func (FlowProtos) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{0}
}

type FlowSafetype int32

const (
	FlowSafetype_FS_UNSET    FlowSafetype = 0
	FlowSafetype_FS_SAFE     FlowSafetype = 1
	FlowSafetype_FS_WARNING  FlowSafetype = 2
	FlowSafetype_FS_DANGER   FlowSafetype = 3
	FlowSafetype_FS_UNCHECK  FlowSafetype = 4
	FlowSafetype_FS_CHECKING FlowSafetype = 5
)

var FlowSafetype_name = map[int32]string{
	0: "FS_UNSET",
	1: "FS_SAFE",
	2: "FS_WARNING",
	3: "FS_DANGER",
	4: "FS_UNCHECK",
	5: "FS_CHECKING",
}

var FlowSafetype_value = map[string]int32{
	"FS_UNSET":    0,
	"FS_SAFE":     1,
	"FS_WARNING":  2,
	"FS_DANGER":   3,
	"FS_UNCHECK":  4,
	"FS_CHECKING": 5,
}

func (x FlowSafetype) String() string {
	return proto.EnumName(FlowSafetype_name, int32(x))
}

func (FlowSafetype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{1}
}

type FlowStat int32

const (
	FlowStat_FST_UNSET  FlowStat = 0
	FlowStat_FST_ACTIVE FlowStat = 1
	FlowStat_FST_FINISH FlowStat = 2
	FlowStat_FST_IDLE   FlowStat = 3
)

var FlowStat_name = map[int32]string{
	0: "FST_UNSET",
	1: "FST_ACTIVE",
	2: "FST_FINISH",
	3: "FST_IDLE",
}

var FlowStat_value = map[string]int32{
	"FST_UNSET":  0,
	"FST_ACTIVE": 1,
	"FST_FINISH": 2,
	"FST_IDLE":   3,
}

func (x FlowStat) String() string {
	return proto.EnumName(FlowStat_name, int32(x))
}

func (FlowStat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2}
}

type GWResult_ActionType int32

const (
	GWResult_DEFAULT          GWResult_ActionType = 0
	GWResult_DEVICE           GWResult_ActionType = 1
	GWResult_THREAT           GWResult_ActionType = 2
	GWResult_GW_INFO          GWResult_ActionType = 3
	GWResult_SAMPLE           GWResult_ActionType = 4
	GWResult_PROTECT          GWResult_ActionType = 5
	GWResult_STRATEGY         GWResult_ActionType = 6
	GWResult_PORTREDIRECT     GWResult_ActionType = 7
	GWResult_DEPLOYER         GWResult_ActionType = 8
	GWResult_FIRMWARE         GWResult_ActionType = 9
	GWResult_FLOWSTAT         GWResult_ActionType = 10
	GWResult_FLOWSTRATEGYSTAT GWResult_ActionType = 11
	GWResult_MONITORINFO      GWResult_ActionType = 12
	GWResult_FLOWSTATISTIC    GWResult_ActionType = 13
)

var GWResult_ActionType_name = map[int32]string{
	0:  "DEFAULT",
	1:  "DEVICE",
	2:  "THREAT",
	3:  "GW_INFO",
	4:  "SAMPLE",
	5:  "PROTECT",
	6:  "STRATEGY",
	7:  "PORTREDIRECT",
	8:  "DEPLOYER",
	9:  "FIRMWARE",
	10: "FLOWSTAT",
	11: "FLOWSTRATEGYSTAT",
	12: "MONITORINFO",
	13: "FLOWSTATISTIC",
}

var GWResult_ActionType_value = map[string]int32{
	"DEFAULT":          0,
	"DEVICE":           1,
	"THREAT":           2,
	"GW_INFO":          3,
	"SAMPLE":           4,
	"PROTECT":          5,
	"STRATEGY":         6,
	"PORTREDIRECT":     7,
	"DEPLOYER":         8,
	"FIRMWARE":         9,
	"FLOWSTAT":         10,
	"FLOWSTRATEGYSTAT": 11,
	"MONITORINFO":      12,
	"FLOWSTATISTIC":    13,
}

func (x GWResult_ActionType) String() string {
	return proto.EnumName(GWResult_ActionType_name, int32(x))
}

func (GWResult_ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{0, 0}
}

type FirwareParam_Status int32

const (
	FirwareParam_DEFAULT           FirwareParam_Status = 0
	FirwareParam_UPGRADING         FirwareParam_Status = 1
	FirwareParam_FIRWARE_INVALID   FirwareParam_Status = 2
	FirwareParam_URL_INVALID       FirwareParam_Status = 3
	FirwareParam_DOWNLOAD_ING      FirwareParam_Status = 4
	FirwareParam_DOWNLOAD_FINISHED FirwareParam_Status = 5
	FirwareParam_DOWNLOAD_FAIL     FirwareParam_Status = 6
	FirwareParam_MD5_ERR           FirwareParam_Status = 7
	FirwareParam_CHECK_OK          FirwareParam_Status = 8
	FirwareParam_EXEC_FAIL         FirwareParam_Status = 9
)

var FirwareParam_Status_name = map[int32]string{
	0: "DEFAULT",
	1: "UPGRADING",
	2: "FIRWARE_INVALID",
	3: "URL_INVALID",
	4: "DOWNLOAD_ING",
	5: "DOWNLOAD_FINISHED",
	6: "DOWNLOAD_FAIL",
	7: "MD5_ERR",
	8: "CHECK_OK",
	9: "EXEC_FAIL",
}

var FirwareParam_Status_value = map[string]int32{
	"DEFAULT":           0,
	"UPGRADING":         1,
	"FIRWARE_INVALID":   2,
	"URL_INVALID":       3,
	"DOWNLOAD_ING":      4,
	"DOWNLOAD_FINISHED": 5,
	"DOWNLOAD_FAIL":     6,
	"MD5_ERR":           7,
	"CHECK_OK":          8,
	"EXEC_FAIL":         9,
}

func (x FirwareParam_Status) String() string {
	return proto.EnumName(FirwareParam_Status_name, int32(x))
}

func (FirwareParam_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{4, 0}
}

type GwInfoParam_Type int32

const (
	GwInfoParam_DEFAULT   GwInfoParam_Type = 0
	GwInfoParam_VSMART    GwInfoParam_Type = 1
	GwInfoParam_VHALO     GwInfoParam_Type = 2
	GwInfoParam_VWIFI     GwInfoParam_Type = 3
	GwInfoParam_VENUSHALO GwInfoParam_Type = 4
)

var GwInfoParam_Type_name = map[int32]string{
	0: "DEFAULT",
	1: "VSMART",
	2: "VHALO",
	3: "VWIFI",
	4: "VENUSHALO",
}

var GwInfoParam_Type_value = map[string]int32{
	"DEFAULT":   0,
	"VSMART":    1,
	"VHALO":     2,
	"VWIFI":     3,
	"VENUSHALO": 4,
}

func (x GwInfoParam_Type) String() string {
	return proto.EnumName(GwInfoParam_Type_name, int32(x))
}

func (GwInfoParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{5, 0}
}

type GwInfoParam_DeployMode int32

const (
	GwInfoParam_DEPLOYMODEDEFAULT GwInfoParam_DeployMode = 0
	GwInfoParam_ROUTEMODE         GwInfoParam_DeployMode = 1
	GwInfoParam_SWITCHMODE        GwInfoParam_DeployMode = 2
)

var GwInfoParam_DeployMode_name = map[int32]string{
	0: "DEPLOYMODEDEFAULT",
	1: "ROUTEMODE",
	2: "SWITCHMODE",
}

var GwInfoParam_DeployMode_value = map[string]int32{
	"DEPLOYMODEDEFAULT": 0,
	"ROUTEMODE":         1,
	"SWITCHMODE":        2,
}

func (x GwInfoParam_DeployMode) String() string {
	return proto.EnumName(GwInfoParam_DeployMode_name, int32(x))
}

func (GwInfoParam_DeployMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{5, 1}
}

type ThreatParam_Item_Type int32

const (
	ThreatParam_Item_DEFAULT          ThreatParam_Item_Type = 0
	ThreatParam_Item_SITE             ThreatParam_Item_Type = 1
	ThreatParam_Item_IP               ThreatParam_Item_Type = 2
	ThreatParam_Item_DNSHIJACK        ThreatParam_Item_Type = 3
	ThreatParam_Item_UDEVICEWHITEIP   ThreatParam_Item_Type = 4
	ThreatParam_Item_UDEVICEWHITESITE ThreatParam_Item_Type = 5
	ThreatParam_Item_UDEVICEBLACKIP   ThreatParam_Item_Type = 6
	ThreatParam_Item_UDEVICEBLACKSITE ThreatParam_Item_Type = 7
	ThreatParam_Item_LANINTRUSION     ThreatParam_Item_Type = 8
	ThreatParam_Item_UDEVLANINTRUSION ThreatParam_Item_Type = 9
)

var ThreatParam_Item_Type_name = map[int32]string{
	0: "DEFAULT",
	1: "SITE",
	2: "IP",
	3: "DNSHIJACK",
	4: "UDEVICEWHITEIP",
	5: "UDEVICEWHITESITE",
	6: "UDEVICEBLACKIP",
	7: "UDEVICEBLACKSITE",
	8: "LANINTRUSION",
	9: "UDEVLANINTRUSION",
}

var ThreatParam_Item_Type_value = map[string]int32{
	"DEFAULT":          0,
	"SITE":             1,
	"IP":               2,
	"DNSHIJACK":        3,
	"UDEVICEWHITEIP":   4,
	"UDEVICEWHITESITE": 5,
	"UDEVICEBLACKIP":   6,
	"UDEVICEBLACKSITE": 7,
	"LANINTRUSION":     8,
	"UDEVLANINTRUSION": 9,
}

func (x ThreatParam_Item_Type) String() string {
	return proto.EnumName(ThreatParam_Item_Type_name, int32(x))
}

func (ThreatParam_Item_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{7, 0, 0}
}

type ThreatParam_Item_Status int32

const (
	ThreatParam_Item_UNKNOWN ThreatParam_Item_Status = 0
	ThreatParam_Item_FOUND   ThreatParam_Item_Status = 1
	ThreatParam_Item_PREVENT ThreatParam_Item_Status = 2
	ThreatParam_Item_WARNING ThreatParam_Item_Status = 3
)

var ThreatParam_Item_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "FOUND",
	2: "PREVENT",
	3: "WARNING",
}

var ThreatParam_Item_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"FOUND":   1,
	"PREVENT": 2,
	"WARNING": 3,
}

func (x ThreatParam_Item_Status) String() string {
	return proto.EnumName(ThreatParam_Item_Status_name, int32(x))
}

func (ThreatParam_Item_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{7, 0, 1}
}

type SampleParam_Status int32

const (
	SampleParam_STATUSDEFAULT  SampleParam_Status = 0
	SampleParam_COLLECTING     SampleParam_Status = 1
	SampleParam_COLLECT_OK     SampleParam_Status = 2
	SampleParam_COLLECT_FAILED SampleParam_Status = 3
)

var SampleParam_Status_name = map[int32]string{
	0: "STATUSDEFAULT",
	1: "COLLECTING",
	2: "COLLECT_OK",
	3: "COLLECT_FAILED",
}

var SampleParam_Status_value = map[string]int32{
	"STATUSDEFAULT":  0,
	"COLLECTING":     1,
	"COLLECT_OK":     2,
	"COLLECT_FAILED": 3,
}

func (x SampleParam_Status) String() string {
	return proto.EnumName(SampleParam_Status_name, int32(x))
}

func (SampleParam_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{8, 0}
}

type GWProtectInfoParam_Status int32

const (
	GWProtectInfoParam_DEFAULT     GWProtectInfoParam_Status = 0
	GWProtectInfoParam_PROTECTING  GWProtectInfoParam_Status = 1
	GWProtectInfoParam_UNPROTECTED GWProtectInfoParam_Status = 2
)

var GWProtectInfoParam_Status_name = map[int32]string{
	0: "DEFAULT",
	1: "PROTECTING",
	2: "UNPROTECTED",
}

var GWProtectInfoParam_Status_value = map[string]int32{
	"DEFAULT":     0,
	"PROTECTING":  1,
	"UNPROTECTED": 2,
}

func (x GWProtectInfoParam_Status) String() string {
	return proto.EnumName(GWProtectInfoParam_Status_name, int32(x))
}

func (GWProtectInfoParam_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{9, 0}
}

type StrategyParam_Type int32

const (
	StrategyParam_TYPEDEFAULT StrategyParam_Type = 0
	StrategyParam_WHITEMODE   StrategyParam_Type = 1
	StrategyParam_BLACKMODE   StrategyParam_Type = 2
)

var StrategyParam_Type_name = map[int32]string{
	0: "TYPEDEFAULT",
	1: "WHITEMODE",
	2: "BLACKMODE",
}

var StrategyParam_Type_value = map[string]int32{
	"TYPEDEFAULT": 0,
	"WHITEMODE":   1,
	"BLACKMODE":   2,
}

func (x StrategyParam_Type) String() string {
	return proto.EnumName(StrategyParam_Type_name, int32(x))
}

func (StrategyParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{10, 0}
}

type StrategyParam_HandleMode int32

const (
	StrategyParam_MODEDEFAULT    StrategyParam_HandleMode = 0
	StrategyParam_PREVENTWARNING StrategyParam_HandleMode = 1
	StrategyParam_WARNING        StrategyParam_HandleMode = 2
)

var StrategyParam_HandleMode_name = map[int32]string{
	0: "MODEDEFAULT",
	1: "PREVENTWARNING",
	2: "WARNING",
}

var StrategyParam_HandleMode_value = map[string]int32{
	"MODEDEFAULT":    0,
	"PREVENTWARNING": 1,
	"WARNING":        2,
}

func (x StrategyParam_HandleMode) String() string {
	return proto.EnumName(StrategyParam_HandleMode_name, int32(x))
}

func (StrategyParam_HandleMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{10, 1}
}

type FlowStrategyParam_Type int32

const (
	FlowStrategyParam_FLWOTYPEDEFAULT FlowStrategyParam_Type = 0
	FlowStrategyParam_FLWOWHITEMODE   FlowStrategyParam_Type = 1
	FlowStrategyParam_FLWOBLACKMODE   FlowStrategyParam_Type = 2
)

var FlowStrategyParam_Type_name = map[int32]string{
	0: "FLWOTYPEDEFAULT",
	1: "FLWOWHITEMODE",
	2: "FLWOBLACKMODE",
}

var FlowStrategyParam_Type_value = map[string]int32{
	"FLWOTYPEDEFAULT": 0,
	"FLWOWHITEMODE":   1,
	"FLWOBLACKMODE":   2,
}

func (x FlowStrategyParam_Type) String() string {
	return proto.EnumName(FlowStrategyParam_Type_name, int32(x))
}

func (FlowStrategyParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{11, 0}
}

type FlowStrategyParam_HandleMode int32

const (
	FlowStrategyParam_MODEDEFAULT    FlowStrategyParam_HandleMode = 0
	FlowStrategyParam_PREVENTWARNING FlowStrategyParam_HandleMode = 1
	FlowStrategyParam_WARNING        FlowStrategyParam_HandleMode = 2
)

var FlowStrategyParam_HandleMode_name = map[int32]string{
	0: "MODEDEFAULT",
	1: "PREVENTWARNING",
	2: "WARNING",
}

var FlowStrategyParam_HandleMode_value = map[string]int32{
	"MODEDEFAULT":    0,
	"PREVENTWARNING": 1,
	"WARNING":        2,
}

func (x FlowStrategyParam_HandleMode) String() string {
	return proto.EnumName(FlowStrategyParam_HandleMode_name, int32(x))
}

func (FlowStrategyParam_HandleMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{11, 1}
}

type PortRedirectParam_Item_Protocol int32

const (
	PortRedirectParam_Item_UNSET PortRedirectParam_Item_Protocol = 0
	PortRedirectParam_Item_UDP   PortRedirectParam_Item_Protocol = 1
	PortRedirectParam_Item_TCP   PortRedirectParam_Item_Protocol = 2
	PortRedirectParam_Item_ALL   PortRedirectParam_Item_Protocol = 3
)

var PortRedirectParam_Item_Protocol_name = map[int32]string{
	0: "UNSET",
	1: "UDP",
	2: "TCP",
	3: "ALL",
}

var PortRedirectParam_Item_Protocol_value = map[string]int32{
	"UNSET": 0,
	"UDP":   1,
	"TCP":   2,
	"ALL":   3,
}

func (x PortRedirectParam_Item_Protocol) String() string {
	return proto.EnumName(PortRedirectParam_Item_Protocol_name, int32(x))
}

func (PortRedirectParam_Item_Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{12, 0, 0}
}

//小v请求的基本格式
type GWResult struct {
	ActionType           GWResult_ActionType `protobuf:"varint,1,opt,name=action_type,json=actionType,proto3,enum=GWResult_ActionType" json:"action_type,omitempty"`
	Param                []byte              `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	GUID                 string              `protobuf:"bytes,3,opt,name=GUID,proto3" json:"GUID,omitempty"`
	CmdID                string              `protobuf:"bytes,4,opt,name=cmdID,proto3" json:"cmdID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GWResult) Reset()         { *m = GWResult{} }
func (m *GWResult) String() string { return proto.CompactTextString(m) }
func (*GWResult) ProtoMessage()    {}
func (*GWResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{0}
}

func (m *GWResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GWResult.Unmarshal(m, b)
}
func (m *GWResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GWResult.Marshal(b, m, deterministic)
}
func (m *GWResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GWResult.Merge(m, src)
}
func (m *GWResult) XXX_Size() int {
	return xxx_messageInfo_GWResult.Size(m)
}
func (m *GWResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GWResult.DiscardUnknown(m)
}

var xxx_messageInfo_GWResult proto.InternalMessageInfo

func (m *GWResult) GetActionType() GWResult_ActionType {
	if m != nil {
		return m.ActionType
	}
	return GWResult_DEFAULT
}

func (m *GWResult) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *GWResult) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func (m *GWResult) GetCmdID() string {
	if m != nil {
		return m.CmdID
	}
	return ""
}

type FlowStatisticParam struct {
	InterfaceName        string   `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Rx                   uint64   `protobuf:"varint,2,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx                   uint64   `protobuf:"varint,3,opt,name=tx,proto3" json:"tx,omitempty"`
	FlowCount            uint32   `protobuf:"varint,4,opt,name=flow_count,json=flowCount,proto3" json:"flow_count,omitempty"`
	Pub                  uint32   `protobuf:"varint,5,opt,name=pub,proto3" json:"pub,omitempty"`
	Notlocal             uint32   `protobuf:"varint,6,opt,name=notlocal,proto3" json:"notlocal,omitempty"`
	White                uint32   `protobuf:"varint,7,opt,name=white,proto3" json:"white,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowStatisticParam) Reset()         { *m = FlowStatisticParam{} }
func (m *FlowStatisticParam) String() string { return proto.CompactTextString(m) }
func (*FlowStatisticParam) ProtoMessage()    {}
func (*FlowStatisticParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{1}
}

func (m *FlowStatisticParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowStatisticParam.Unmarshal(m, b)
}
func (m *FlowStatisticParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowStatisticParam.Marshal(b, m, deterministic)
}
func (m *FlowStatisticParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowStatisticParam.Merge(m, src)
}
func (m *FlowStatisticParam) XXX_Size() int {
	return xxx_messageInfo_FlowStatisticParam.Size(m)
}
func (m *FlowStatisticParam) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowStatisticParam.DiscardUnknown(m)
}

var xxx_messageInfo_FlowStatisticParam proto.InternalMessageInfo

func (m *FlowStatisticParam) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *FlowStatisticParam) GetRx() uint64 {
	if m != nil {
		return m.Rx
	}
	return 0
}

func (m *FlowStatisticParam) GetTx() uint64 {
	if m != nil {
		return m.Tx
	}
	return 0
}

func (m *FlowStatisticParam) GetFlowCount() uint32 {
	if m != nil {
		return m.FlowCount
	}
	return 0
}

func (m *FlowStatisticParam) GetPub() uint32 {
	if m != nil {
		return m.Pub
	}
	return 0
}

func (m *FlowStatisticParam) GetNotlocal() uint32 {
	if m != nil {
		return m.Notlocal
	}
	return 0
}

func (m *FlowStatisticParam) GetWhite() uint32 {
	if m != nil {
		return m.White
	}
	return 0
}

type MonitorInfoParam struct {
	RedisInfo            *MonitorInfoParam_RedisInfo      `protobuf:"bytes,1,opt,name=redis_info,json=redisInfo,proto3" json:"redis_info,omitempty"`
	VhaloInfo            *MonitorInfoParam_VHaloNets      `protobuf:"bytes,2,opt,name=vhalo_info,json=vhaloInfo,proto3" json:"vhalo_info,omitempty"`
	DiskItem             []*MonitorInfoParam_DiskOverFlow `protobuf:"bytes,3,rep,name=disk_item,json=diskItem,proto3" json:"disk_item,omitempty"`
	GatherTime           uint64                           `protobuf:"varint,4,opt,name=gather_time,json=gatherTime,proto3" json:"gather_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *MonitorInfoParam) Reset()         { *m = MonitorInfoParam{} }
func (m *MonitorInfoParam) String() string { return proto.CompactTextString(m) }
func (*MonitorInfoParam) ProtoMessage()    {}
func (*MonitorInfoParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2}
}

func (m *MonitorInfoParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorInfoParam.Unmarshal(m, b)
}
func (m *MonitorInfoParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorInfoParam.Marshal(b, m, deterministic)
}
func (m *MonitorInfoParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorInfoParam.Merge(m, src)
}
func (m *MonitorInfoParam) XXX_Size() int {
	return xxx_messageInfo_MonitorInfoParam.Size(m)
}
func (m *MonitorInfoParam) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorInfoParam.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorInfoParam proto.InternalMessageInfo

func (m *MonitorInfoParam) GetRedisInfo() *MonitorInfoParam_RedisInfo {
	if m != nil {
		return m.RedisInfo
	}
	return nil
}

func (m *MonitorInfoParam) GetVhaloInfo() *MonitorInfoParam_VHaloNets {
	if m != nil {
		return m.VhaloInfo
	}
	return nil
}

func (m *MonitorInfoParam) GetDiskItem() []*MonitorInfoParam_DiskOverFlow {
	if m != nil {
		return m.DiskItem
	}
	return nil
}

func (m *MonitorInfoParam) GetGatherTime() uint64 {
	if m != nil {
		return m.GatherTime
	}
	return 0
}

type MonitorInfoParam_DiskOverFlow struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DiskRate             float32  `protobuf:"fixed32,2,opt,name=disk_rate,json=diskRate,proto3" json:"disk_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorInfoParam_DiskOverFlow) Reset()         { *m = MonitorInfoParam_DiskOverFlow{} }
func (m *MonitorInfoParam_DiskOverFlow) String() string { return proto.CompactTextString(m) }
func (*MonitorInfoParam_DiskOverFlow) ProtoMessage()    {}
func (*MonitorInfoParam_DiskOverFlow) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2, 0}
}

func (m *MonitorInfoParam_DiskOverFlow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorInfoParam_DiskOverFlow.Unmarshal(m, b)
}
func (m *MonitorInfoParam_DiskOverFlow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorInfoParam_DiskOverFlow.Marshal(b, m, deterministic)
}
func (m *MonitorInfoParam_DiskOverFlow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorInfoParam_DiskOverFlow.Merge(m, src)
}
func (m *MonitorInfoParam_DiskOverFlow) XXX_Size() int {
	return xxx_messageInfo_MonitorInfoParam_DiskOverFlow.Size(m)
}
func (m *MonitorInfoParam_DiskOverFlow) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorInfoParam_DiskOverFlow.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorInfoParam_DiskOverFlow proto.InternalMessageInfo

func (m *MonitorInfoParam_DiskOverFlow) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *MonitorInfoParam_DiskOverFlow) GetDiskRate() float32 {
	if m != nil {
		return m.DiskRate
	}
	return 0
}

type MonitorInfoParam_RedisInfo struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	CpuRate              float32  `protobuf:"fixed32,2,opt,name=cpu_rate,json=cpuRate,proto3" json:"cpu_rate,omitempty"`
	MemRate              float32  `protobuf:"fixed32,3,opt,name=mem_rate,json=memRate,proto3" json:"mem_rate,omitempty"`
	Mem                  uint64   `protobuf:"varint,4,opt,name=mem,proto3" json:"mem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorInfoParam_RedisInfo) Reset()         { *m = MonitorInfoParam_RedisInfo{} }
func (m *MonitorInfoParam_RedisInfo) String() string { return proto.CompactTextString(m) }
func (*MonitorInfoParam_RedisInfo) ProtoMessage()    {}
func (*MonitorInfoParam_RedisInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2, 1}
}

func (m *MonitorInfoParam_RedisInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorInfoParam_RedisInfo.Unmarshal(m, b)
}
func (m *MonitorInfoParam_RedisInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorInfoParam_RedisInfo.Marshal(b, m, deterministic)
}
func (m *MonitorInfoParam_RedisInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorInfoParam_RedisInfo.Merge(m, src)
}
func (m *MonitorInfoParam_RedisInfo) XXX_Size() int {
	return xxx_messageInfo_MonitorInfoParam_RedisInfo.Size(m)
}
func (m *MonitorInfoParam_RedisInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorInfoParam_RedisInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorInfoParam_RedisInfo proto.InternalMessageInfo

func (m *MonitorInfoParam_RedisInfo) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *MonitorInfoParam_RedisInfo) GetCpuRate() float32 {
	if m != nil {
		return m.CpuRate
	}
	return 0
}

func (m *MonitorInfoParam_RedisInfo) GetMemRate() float32 {
	if m != nil {
		return m.MemRate
	}
	return 0
}

func (m *MonitorInfoParam_RedisInfo) GetMem() uint64 {
	if m != nil {
		return m.Mem
	}
	return 0
}

type MonitorInfoParam_VHaloNets struct {
	Active               bool     `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	CpuRate              float32  `protobuf:"fixed32,2,opt,name=cpu_rate,json=cpuRate,proto3" json:"cpu_rate,omitempty"`
	MemRate              float32  `protobuf:"fixed32,3,opt,name=mem_rate,json=memRate,proto3" json:"mem_rate,omitempty"`
	Mem                  uint64   `protobuf:"varint,4,opt,name=mem,proto3" json:"mem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorInfoParam_VHaloNets) Reset()         { *m = MonitorInfoParam_VHaloNets{} }
func (m *MonitorInfoParam_VHaloNets) String() string { return proto.CompactTextString(m) }
func (*MonitorInfoParam_VHaloNets) ProtoMessage()    {}
func (*MonitorInfoParam_VHaloNets) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{2, 2}
}

func (m *MonitorInfoParam_VHaloNets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorInfoParam_VHaloNets.Unmarshal(m, b)
}
func (m *MonitorInfoParam_VHaloNets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorInfoParam_VHaloNets.Marshal(b, m, deterministic)
}
func (m *MonitorInfoParam_VHaloNets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorInfoParam_VHaloNets.Merge(m, src)
}
func (m *MonitorInfoParam_VHaloNets) XXX_Size() int {
	return xxx_messageInfo_MonitorInfoParam_VHaloNets.Size(m)
}
func (m *MonitorInfoParam_VHaloNets) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorInfoParam_VHaloNets.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorInfoParam_VHaloNets proto.InternalMessageInfo

func (m *MonitorInfoParam_VHaloNets) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *MonitorInfoParam_VHaloNets) GetCpuRate() float32 {
	if m != nil {
		return m.CpuRate
	}
	return 0
}

func (m *MonitorInfoParam_VHaloNets) GetMemRate() float32 {
	if m != nil {
		return m.MemRate
	}
	return 0
}

func (m *MonitorInfoParam_VHaloNets) GetMem() uint64 {
	if m != nil {
		return m.Mem
	}
	return 0
}

type FlowParam struct {
	FlowItem             []*FlowParam_FItem `protobuf:"bytes,1,rep,name=flow_item,json=flowItem,proto3" json:"flow_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FlowParam) Reset()         { *m = FlowParam{} }
func (m *FlowParam) String() string { return proto.CompactTextString(m) }
func (*FlowParam) ProtoMessage()    {}
func (*FlowParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{3}
}

func (m *FlowParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowParam.Unmarshal(m, b)
}
func (m *FlowParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowParam.Marshal(b, m, deterministic)
}
func (m *FlowParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowParam.Merge(m, src)
}
func (m *FlowParam) XXX_Size() int {
	return xxx_messageInfo_FlowParam.Size(m)
}
func (m *FlowParam) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowParam.DiscardUnknown(m)
}

var xxx_messageInfo_FlowParam proto.InternalMessageInfo

func (m *FlowParam) GetFlowItem() []*FlowParam_FItem {
	if m != nil {
		return m.FlowItem
	}
	return nil
}

type FlowParam_FItem struct {
	Hash                 uint32       `protobuf:"varint,1,opt,name=hash,proto3" json:"hash,omitempty"`
	SrcIp                uint32       `protobuf:"varint,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort              uint32       `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp                uint32       `protobuf:"varint,4,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort              uint32       `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol             FlowProtos   `protobuf:"varint,6,opt,name=protocol,proto3,enum=FlowProtos" json:"protocol,omitempty"`
	FlowInfo             string       `protobuf:"bytes,7,opt,name=flow_info,json=flowInfo,proto3" json:"flow_info,omitempty"`
	SafeType             FlowSafetype `protobuf:"varint,8,opt,name=safe_type,json=safeType,proto3,enum=FlowSafetype" json:"safe_type,omitempty"`
	SafeInfo             string       `protobuf:"bytes,9,opt,name=safe_info,json=safeInfo,proto3" json:"safe_info,omitempty"`
	StartTime            uint32       `protobuf:"varint,10,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	LastSeenTime         uint32       `protobuf:"varint,11,opt,name=last_seen_time,json=lastSeenTime,proto3" json:"last_seen_time,omitempty"`
	Src2DstBytes         uint64       `protobuf:"varint,12,opt,name=src2dst_bytes,json=src2dstBytes,proto3" json:"src2dst_bytes,omitempty"`
	Dst2SrcBytes         uint64       `protobuf:"varint,13,opt,name=dst2src_bytes,json=dst2srcBytes,proto3" json:"dst2src_bytes,omitempty"`
	FlowStat             FlowStat     `protobuf:"varint,14,opt,name=flow_stat,json=flowStat,proto3,enum=FlowStat" json:"flow_stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FlowParam_FItem) Reset()         { *m = FlowParam_FItem{} }
func (m *FlowParam_FItem) String() string { return proto.CompactTextString(m) }
func (*FlowParam_FItem) ProtoMessage()    {}
func (*FlowParam_FItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{3, 0}
}

func (m *FlowParam_FItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowParam_FItem.Unmarshal(m, b)
}
func (m *FlowParam_FItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowParam_FItem.Marshal(b, m, deterministic)
}
func (m *FlowParam_FItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowParam_FItem.Merge(m, src)
}
func (m *FlowParam_FItem) XXX_Size() int {
	return xxx_messageInfo_FlowParam_FItem.Size(m)
}
func (m *FlowParam_FItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowParam_FItem.DiscardUnknown(m)
}

var xxx_messageInfo_FlowParam_FItem proto.InternalMessageInfo

func (m *FlowParam_FItem) GetHash() uint32 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *FlowParam_FItem) GetSrcIp() uint32 {
	if m != nil {
		return m.SrcIp
	}
	return 0
}

func (m *FlowParam_FItem) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *FlowParam_FItem) GetDstIp() uint32 {
	if m != nil {
		return m.DstIp
	}
	return 0
}

func (m *FlowParam_FItem) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *FlowParam_FItem) GetProtocol() FlowProtos {
	if m != nil {
		return m.Protocol
	}
	return FlowProtos_FP_UNKNOWN
}

func (m *FlowParam_FItem) GetFlowInfo() string {
	if m != nil {
		return m.FlowInfo
	}
	return ""
}

func (m *FlowParam_FItem) GetSafeType() FlowSafetype {
	if m != nil {
		return m.SafeType
	}
	return FlowSafetype_FS_UNSET
}

func (m *FlowParam_FItem) GetSafeInfo() string {
	if m != nil {
		return m.SafeInfo
	}
	return ""
}

func (m *FlowParam_FItem) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *FlowParam_FItem) GetLastSeenTime() uint32 {
	if m != nil {
		return m.LastSeenTime
	}
	return 0
}

func (m *FlowParam_FItem) GetSrc2DstBytes() uint64 {
	if m != nil {
		return m.Src2DstBytes
	}
	return 0
}

func (m *FlowParam_FItem) GetDst2SrcBytes() uint64 {
	if m != nil {
		return m.Dst2SrcBytes
	}
	return 0
}

func (m *FlowParam_FItem) GetFlowStat() FlowStat {
	if m != nil {
		return m.FlowStat
	}
	return FlowStat_FST_UNSET
}

type FirwareParam struct {
	Version              string              `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	UpgradeTimestamp     uint32              `protobuf:"varint,2,opt,name=upgrade_timestamp,json=upgradeTimestamp,proto3" json:"upgrade_timestamp,omitempty"`
	UpgradeStatus        FirwareParam_Status `protobuf:"varint,3,opt,name=upgrade_status,json=upgradeStatus,proto3,enum=FirwareParam_Status" json:"upgrade_status,omitempty"`
	Timeout              uint32              `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *FirwareParam) Reset()         { *m = FirwareParam{} }
func (m *FirwareParam) String() string { return proto.CompactTextString(m) }
func (*FirwareParam) ProtoMessage()    {}
func (*FirwareParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{4}
}

func (m *FirwareParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirwareParam.Unmarshal(m, b)
}
func (m *FirwareParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirwareParam.Marshal(b, m, deterministic)
}
func (m *FirwareParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirwareParam.Merge(m, src)
}
func (m *FirwareParam) XXX_Size() int {
	return xxx_messageInfo_FirwareParam.Size(m)
}
func (m *FirwareParam) XXX_DiscardUnknown() {
	xxx_messageInfo_FirwareParam.DiscardUnknown(m)
}

var xxx_messageInfo_FirwareParam proto.InternalMessageInfo

func (m *FirwareParam) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *FirwareParam) GetUpgradeTimestamp() uint32 {
	if m != nil {
		return m.UpgradeTimestamp
	}
	return 0
}

func (m *FirwareParam) GetUpgradeStatus() FirwareParam_Status {
	if m != nil {
		return m.UpgradeStatus
	}
	return FirwareParam_DEFAULT
}

func (m *FirwareParam) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

//小v盒子的基本信息
type GwInfoParam struct {
	Version              string                    `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	StartTime            uint32                    `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	FirmwareVersion      string                    `protobuf:"bytes,3,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	HardwareModel        string                    `protobuf:"bytes,4,opt,name=hardware_model,json=hardwareModel,proto3" json:"hardware_model,omitempty"`
	Module               []*GwInfoParam_ModuleItem `protobuf:"bytes,5,rep,name=module,proto3" json:"module,omitempty"`
	SupplyId             string                    `protobuf:"bytes,6,opt,name=supply_id,json=supplyId,proto3" json:"supply_id,omitempty"`
	UpRouterIp           string                    `protobuf:"bytes,7,opt,name=up_router_ip,json=upRouterIp,proto3" json:"up_router_ip,omitempty"`
	Ip                   string                    `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	Type                 GwInfoParam_Type          `protobuf:"varint,9,opt,name=type,proto3,enum=GwInfoParam_Type" json:"type,omitempty"`
	Mac                  string                    `protobuf:"bytes,10,opt,name=mac,proto3" json:"mac,omitempty"`
	Timestamp            uint32                    `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HbTimeout            int32                     `protobuf:"varint,12,opt,name=hb_timeout,json=hbTimeout,proto3" json:"hb_timeout,omitempty"`
	DeployMode           GwInfoParam_DeployMode    `protobuf:"varint,13,opt,name=deploy_mode,json=deployMode,proto3,enum=GwInfoParam_DeployMode" json:"deploy_mode,omitempty"`
	FlowIdleTimeSlot     uint32                    `protobuf:"varint,14,opt,name=flow_idle_time_slot,json=flowIdleTimeSlot,proto3" json:"flow_idle_time_slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GwInfoParam) Reset()         { *m = GwInfoParam{} }
func (m *GwInfoParam) String() string { return proto.CompactTextString(m) }
func (*GwInfoParam) ProtoMessage()    {}
func (*GwInfoParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{5}
}

func (m *GwInfoParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwInfoParam.Unmarshal(m, b)
}
func (m *GwInfoParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwInfoParam.Marshal(b, m, deterministic)
}
func (m *GwInfoParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwInfoParam.Merge(m, src)
}
func (m *GwInfoParam) XXX_Size() int {
	return xxx_messageInfo_GwInfoParam.Size(m)
}
func (m *GwInfoParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GwInfoParam.DiscardUnknown(m)
}

var xxx_messageInfo_GwInfoParam proto.InternalMessageInfo

func (m *GwInfoParam) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GwInfoParam) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GwInfoParam) GetFirmwareVersion() string {
	if m != nil {
		return m.FirmwareVersion
	}
	return ""
}

func (m *GwInfoParam) GetHardwareModel() string {
	if m != nil {
		return m.HardwareModel
	}
	return ""
}

func (m *GwInfoParam) GetModule() []*GwInfoParam_ModuleItem {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *GwInfoParam) GetSupplyId() string {
	if m != nil {
		return m.SupplyId
	}
	return ""
}

func (m *GwInfoParam) GetUpRouterIp() string {
	if m != nil {
		return m.UpRouterIp
	}
	return ""
}

func (m *GwInfoParam) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *GwInfoParam) GetType() GwInfoParam_Type {
	if m != nil {
		return m.Type
	}
	return GwInfoParam_DEFAULT
}

func (m *GwInfoParam) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *GwInfoParam) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GwInfoParam) GetHbTimeout() int32 {
	if m != nil {
		return m.HbTimeout
	}
	return 0
}

func (m *GwInfoParam) GetDeployMode() GwInfoParam_DeployMode {
	if m != nil {
		return m.DeployMode
	}
	return GwInfoParam_DEPLOYMODEDEFAULT
}

func (m *GwInfoParam) GetFlowIdleTimeSlot() uint32 {
	if m != nil {
		return m.FlowIdleTimeSlot
	}
	return 0
}

type GwInfoParam_ModuleItem struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GwInfoParam_ModuleItem) Reset()         { *m = GwInfoParam_ModuleItem{} }
func (m *GwInfoParam_ModuleItem) String() string { return proto.CompactTextString(m) }
func (*GwInfoParam_ModuleItem) ProtoMessage()    {}
func (*GwInfoParam_ModuleItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{5, 0}
}

func (m *GwInfoParam_ModuleItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwInfoParam_ModuleItem.Unmarshal(m, b)
}
func (m *GwInfoParam_ModuleItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwInfoParam_ModuleItem.Marshal(b, m, deterministic)
}
func (m *GwInfoParam_ModuleItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwInfoParam_ModuleItem.Merge(m, src)
}
func (m *GwInfoParam_ModuleItem) XXX_Size() int {
	return xxx_messageInfo_GwInfoParam_ModuleItem.Size(m)
}
func (m *GwInfoParam_ModuleItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GwInfoParam_ModuleItem.DiscardUnknown(m)
}

var xxx_messageInfo_GwInfoParam_ModuleItem proto.InternalMessageInfo

func (m *GwInfoParam_ModuleItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GwInfoParam_ModuleItem) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

//小v下属关联设备（终端）
type DeviceParam struct {
	DeviceItem           []*DeviceParam_Item `protobuf:"bytes,1,rep,name=device_item,json=deviceItem,proto3" json:"device_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DeviceParam) Reset()         { *m = DeviceParam{} }
func (m *DeviceParam) String() string { return proto.CompactTextString(m) }
func (*DeviceParam) ProtoMessage()    {}
func (*DeviceParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{6}
}

func (m *DeviceParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceParam.Unmarshal(m, b)
}
func (m *DeviceParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceParam.Marshal(b, m, deterministic)
}
func (m *DeviceParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceParam.Merge(m, src)
}
func (m *DeviceParam) XXX_Size() int {
	return xxx_messageInfo_DeviceParam.Size(m)
}
func (m *DeviceParam) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceParam.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceParam proto.InternalMessageInfo

func (m *DeviceParam) GetDeviceItem() []*DeviceParam_Item {
	if m != nil {
		return m.DeviceItem
	}
	return nil
}

type DeviceParam_Item struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac                  string   `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Trademark            string   `protobuf:"bytes,4,opt,name=trademark,proto3" json:"trademark,omitempty"`
	IsOnline             bool     `protobuf:"varint,5,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	LastOnline           uint32   `protobuf:"varint,6,opt,name=last_online,json=lastOnline,proto3" json:"last_online,omitempty"`
	InternetSwitch       bool     `protobuf:"varint,7,opt,name=internet_switch,json=internetSwitch,proto3" json:"internet_switch,omitempty"`
	ProtectSwitch        bool     `protobuf:"varint,8,opt,name=protect_switch,json=protectSwitch,proto3" json:"protect_switch,omitempty"`
	LanVisitSwitch       bool     `protobuf:"varint,9,opt,name=lan_visit_switch,json=lanVisitSwitch,proto3" json:"lan_visit_switch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceParam_Item) Reset()         { *m = DeviceParam_Item{} }
func (m *DeviceParam_Item) String() string { return proto.CompactTextString(m) }
func (*DeviceParam_Item) ProtoMessage()    {}
func (*DeviceParam_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{6, 0}
}

func (m *DeviceParam_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceParam_Item.Unmarshal(m, b)
}
func (m *DeviceParam_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceParam_Item.Marshal(b, m, deterministic)
}
func (m *DeviceParam_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceParam_Item.Merge(m, src)
}
func (m *DeviceParam_Item) XXX_Size() int {
	return xxx_messageInfo_DeviceParam_Item.Size(m)
}
func (m *DeviceParam_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceParam_Item.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceParam_Item proto.InternalMessageInfo

func (m *DeviceParam_Item) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *DeviceParam_Item) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *DeviceParam_Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceParam_Item) GetTrademark() string {
	if m != nil {
		return m.Trademark
	}
	return ""
}

func (m *DeviceParam_Item) GetIsOnline() bool {
	if m != nil {
		return m.IsOnline
	}
	return false
}

func (m *DeviceParam_Item) GetLastOnline() uint32 {
	if m != nil {
		return m.LastOnline
	}
	return 0
}

func (m *DeviceParam_Item) GetInternetSwitch() bool {
	if m != nil {
		return m.InternetSwitch
	}
	return false
}

func (m *DeviceParam_Item) GetProtectSwitch() bool {
	if m != nil {
		return m.ProtectSwitch
	}
	return false
}

func (m *DeviceParam_Item) GetLanVisitSwitch() bool {
	if m != nil {
		return m.LanVisitSwitch
	}
	return false
}

//威胁类型
type ThreatParam struct {
	ThreatItem           []*ThreatParam_Item `protobuf:"bytes,1,rep,name=threat_item,json=threatItem,proto3" json:"threat_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ThreatParam) Reset()         { *m = ThreatParam{} }
func (m *ThreatParam) String() string { return proto.CompactTextString(m) }
func (*ThreatParam) ProtoMessage()    {}
func (*ThreatParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{7}
}

func (m *ThreatParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreatParam.Unmarshal(m, b)
}
func (m *ThreatParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreatParam.Marshal(b, m, deterministic)
}
func (m *ThreatParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreatParam.Merge(m, src)
}
func (m *ThreatParam) XXX_Size() int {
	return xxx_messageInfo_ThreatParam.Size(m)
}
func (m *ThreatParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreatParam.DiscardUnknown(m)
}

var xxx_messageInfo_ThreatParam proto.InternalMessageInfo

func (m *ThreatParam) GetThreatItem() []*ThreatParam_Item {
	if m != nil {
		return m.ThreatItem
	}
	return nil
}

//威胁事件object,
type ThreatParam_Item struct {
	SrcMac               string                  `protobuf:"bytes,1,opt,name=src_mac,json=srcMac,proto3" json:"src_mac,omitempty"`
	ThreatType           ThreatParam_Item_Type   `protobuf:"varint,2,opt,name=threat_type,json=threatType,proto3,enum=ThreatParam_Item_Type" json:"threat_type,omitempty"`
	Content              string                  `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ThreatStatus         ThreatParam_Item_Status `protobuf:"varint,4,opt,name=threat_status,json=threatStatus,proto3,enum=ThreatParam_Item_Status" json:"threat_status,omitempty"`
	AttactTime           uint32                  `protobuf:"varint,5,opt,name=attact_time,json=attactTime,proto3" json:"attact_time,omitempty"`
	SrcIp                string                  `protobuf:"bytes,6,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp                string                  `protobuf:"bytes,7,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ThreatParam_Item) Reset()         { *m = ThreatParam_Item{} }
func (m *ThreatParam_Item) String() string { return proto.CompactTextString(m) }
func (*ThreatParam_Item) ProtoMessage()    {}
func (*ThreatParam_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{7, 0}
}

func (m *ThreatParam_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreatParam_Item.Unmarshal(m, b)
}
func (m *ThreatParam_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreatParam_Item.Marshal(b, m, deterministic)
}
func (m *ThreatParam_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreatParam_Item.Merge(m, src)
}
func (m *ThreatParam_Item) XXX_Size() int {
	return xxx_messageInfo_ThreatParam_Item.Size(m)
}
func (m *ThreatParam_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreatParam_Item.DiscardUnknown(m)
}

var xxx_messageInfo_ThreatParam_Item proto.InternalMessageInfo

func (m *ThreatParam_Item) GetSrcMac() string {
	if m != nil {
		return m.SrcMac
	}
	return ""
}

func (m *ThreatParam_Item) GetThreatType() ThreatParam_Item_Type {
	if m != nil {
		return m.ThreatType
	}
	return ThreatParam_Item_DEFAULT
}

func (m *ThreatParam_Item) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ThreatParam_Item) GetThreatStatus() ThreatParam_Item_Status {
	if m != nil {
		return m.ThreatStatus
	}
	return ThreatParam_Item_UNKNOWN
}

func (m *ThreatParam_Item) GetAttactTime() uint32 {
	if m != nil {
		return m.AttactTime
	}
	return 0
}

func (m *ThreatParam_Item) GetSrcIp() string {
	if m != nil {
		return m.SrcIp
	}
	return ""
}

func (m *ThreatParam_Item) GetDstIp() string {
	if m != nil {
		return m.DstIp
	}
	return ""
}

// 样本采集任务状态
type SampleParam struct {
	Id                   string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartTime            uint32              `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TimeRemain           uint32              `protobuf:"varint,3,opt,name=time_remain,json=timeRemain,proto3" json:"time_remain,omitempty"`
	Status               SampleParam_Status  `protobuf:"varint,4,opt,name=status,proto3,enum=SampleParam_Status" json:"status,omitempty"`
	SampleItem           []*SampleParam_Item `protobuf:"bytes,5,rep,name=sample_item,json=sampleItem,proto3" json:"sample_item,omitempty"`
	Timeout              uint32              `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SampleParam) Reset()         { *m = SampleParam{} }
func (m *SampleParam) String() string { return proto.CompactTextString(m) }
func (*SampleParam) ProtoMessage()    {}
func (*SampleParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{8}
}

func (m *SampleParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleParam.Unmarshal(m, b)
}
func (m *SampleParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleParam.Marshal(b, m, deterministic)
}
func (m *SampleParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleParam.Merge(m, src)
}
func (m *SampleParam) XXX_Size() int {
	return xxx_messageInfo_SampleParam.Size(m)
}
func (m *SampleParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleParam.DiscardUnknown(m)
}

var xxx_messageInfo_SampleParam proto.InternalMessageInfo

func (m *SampleParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SampleParam) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *SampleParam) GetTimeRemain() uint32 {
	if m != nil {
		return m.TimeRemain
	}
	return 0
}

func (m *SampleParam) GetStatus() SampleParam_Status {
	if m != nil {
		return m.Status
	}
	return SampleParam_STATUSDEFAULT
}

func (m *SampleParam) GetSampleItem() []*SampleParam_Item {
	if m != nil {
		return m.SampleItem
	}
	return nil
}

func (m *SampleParam) GetTimeout() uint32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type SampleParam_Item struct {
	Sm                   string   `protobuf:"bytes,6,opt,name=sm,proto3" json:"sm,omitempty"`
	Sip                  string   `protobuf:"bytes,7,opt,name=sip,proto3" json:"sip,omitempty"`
	Sp                   uint32   `protobuf:"varint,8,opt,name=sp,proto3" json:"sp,omitempty"`
	Dip                  string   `protobuf:"bytes,9,opt,name=dip,proto3" json:"dip,omitempty"`
	Dp                   uint32   `protobuf:"varint,10,opt,name=dp,proto3" json:"dp,omitempty"`
	U                    string   `protobuf:"bytes,12,opt,name=u,proto3" json:"u,omitempty"`
	Tm                   string   `protobuf:"bytes,13,opt,name=tm,proto3" json:"tm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleParam_Item) Reset()         { *m = SampleParam_Item{} }
func (m *SampleParam_Item) String() string { return proto.CompactTextString(m) }
func (*SampleParam_Item) ProtoMessage()    {}
func (*SampleParam_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{8, 0}
}

func (m *SampleParam_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleParam_Item.Unmarshal(m, b)
}
func (m *SampleParam_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleParam_Item.Marshal(b, m, deterministic)
}
func (m *SampleParam_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleParam_Item.Merge(m, src)
}
func (m *SampleParam_Item) XXX_Size() int {
	return xxx_messageInfo_SampleParam_Item.Size(m)
}
func (m *SampleParam_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleParam_Item.DiscardUnknown(m)
}

var xxx_messageInfo_SampleParam_Item proto.InternalMessageInfo

func (m *SampleParam_Item) GetSm() string {
	if m != nil {
		return m.Sm
	}
	return ""
}

func (m *SampleParam_Item) GetSip() string {
	if m != nil {
		return m.Sip
	}
	return ""
}

func (m *SampleParam_Item) GetSp() uint32 {
	if m != nil {
		return m.Sp
	}
	return 0
}

func (m *SampleParam_Item) GetDip() string {
	if m != nil {
		return m.Dip
	}
	return ""
}

func (m *SampleParam_Item) GetDp() uint32 {
	if m != nil {
		return m.Dp
	}
	return 0
}

func (m *SampleParam_Item) GetU() string {
	if m != nil {
		return m.U
	}
	return ""
}

func (m *SampleParam_Item) GetTm() string {
	if m != nil {
		return m.Tm
	}
	return ""
}

// 小V盒子全局保护状态信息
type GWProtectInfoParam struct {
	ProtectStatus        GWProtectInfoParam_Status `protobuf:"varint,1,opt,name=protect_status,json=protectStatus,proto3,enum=GWProtectInfoParam_Status" json:"protect_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GWProtectInfoParam) Reset()         { *m = GWProtectInfoParam{} }
func (m *GWProtectInfoParam) String() string { return proto.CompactTextString(m) }
func (*GWProtectInfoParam) ProtoMessage()    {}
func (*GWProtectInfoParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{9}
}

func (m *GWProtectInfoParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GWProtectInfoParam.Unmarshal(m, b)
}
func (m *GWProtectInfoParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GWProtectInfoParam.Marshal(b, m, deterministic)
}
func (m *GWProtectInfoParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GWProtectInfoParam.Merge(m, src)
}
func (m *GWProtectInfoParam) XXX_Size() int {
	return xxx_messageInfo_GWProtectInfoParam.Size(m)
}
func (m *GWProtectInfoParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GWProtectInfoParam.DiscardUnknown(m)
}

var xxx_messageInfo_GWProtectInfoParam proto.InternalMessageInfo

func (m *GWProtectInfoParam) GetProtectStatus() GWProtectInfoParam_Status {
	if m != nil {
		return m.ProtectStatus
	}
	return GWProtectInfoParam_DEFAULT
}

// 小V 当前策略的状态
type StrategyParam struct {
	StrategyId           string                   `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	HandleMode           StrategyParam_HandleMode `protobuf:"varint,2,opt,name=handle_mode,json=handleMode,proto3,enum=StrategyParam_HandleMode" json:"handle_mode,omitempty"`
	DefenseType          StrategyParam_Type       `protobuf:"varint,3,opt,name=defense_type,json=defenseType,proto3,enum=StrategyParam_Type" json:"defense_type,omitempty"`
	Enable               bool                     `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StrategyParam) Reset()         { *m = StrategyParam{} }
func (m *StrategyParam) String() string { return proto.CompactTextString(m) }
func (*StrategyParam) ProtoMessage()    {}
func (*StrategyParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{10}
}

func (m *StrategyParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyParam.Unmarshal(m, b)
}
func (m *StrategyParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyParam.Marshal(b, m, deterministic)
}
func (m *StrategyParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyParam.Merge(m, src)
}
func (m *StrategyParam) XXX_Size() int {
	return xxx_messageInfo_StrategyParam.Size(m)
}
func (m *StrategyParam) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyParam.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyParam proto.InternalMessageInfo

func (m *StrategyParam) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *StrategyParam) GetHandleMode() StrategyParam_HandleMode {
	if m != nil {
		return m.HandleMode
	}
	return StrategyParam_MODEDEFAULT
}

func (m *StrategyParam) GetDefenseType() StrategyParam_Type {
	if m != nil {
		return m.DefenseType
	}
	return StrategyParam_TYPEDEFAULT
}

func (m *StrategyParam) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

// 小V 当前策略的状态
type FlowStrategyParam struct {
	FlowStrategyId       string                       `protobuf:"bytes,1,opt,name=flow_strategy_id,json=flowStrategyId,proto3" json:"flow_strategy_id,omitempty"`
	HandleMode           FlowStrategyParam_HandleMode `protobuf:"varint,2,opt,name=handle_mode,json=handleMode,proto3,enum=FlowStrategyParam_HandleMode" json:"handle_mode,omitempty"`
	DefenseType          FlowStrategyParam_Type       `protobuf:"varint,3,opt,name=defense_type,json=defenseType,proto3,enum=FlowStrategyParam_Type" json:"defense_type,omitempty"`
	Enable               bool                         `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FlowStrategyParam) Reset()         { *m = FlowStrategyParam{} }
func (m *FlowStrategyParam) String() string { return proto.CompactTextString(m) }
func (*FlowStrategyParam) ProtoMessage()    {}
func (*FlowStrategyParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{11}
}

func (m *FlowStrategyParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowStrategyParam.Unmarshal(m, b)
}
func (m *FlowStrategyParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowStrategyParam.Marshal(b, m, deterministic)
}
func (m *FlowStrategyParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowStrategyParam.Merge(m, src)
}
func (m *FlowStrategyParam) XXX_Size() int {
	return xxx_messageInfo_FlowStrategyParam.Size(m)
}
func (m *FlowStrategyParam) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowStrategyParam.DiscardUnknown(m)
}

var xxx_messageInfo_FlowStrategyParam proto.InternalMessageInfo

func (m *FlowStrategyParam) GetFlowStrategyId() string {
	if m != nil {
		return m.FlowStrategyId
	}
	return ""
}

func (m *FlowStrategyParam) GetHandleMode() FlowStrategyParam_HandleMode {
	if m != nil {
		return m.HandleMode
	}
	return FlowStrategyParam_MODEDEFAULT
}

func (m *FlowStrategyParam) GetDefenseType() FlowStrategyParam_Type {
	if m != nil {
		return m.DefenseType
	}
	return FlowStrategyParam_FLWOTYPEDEFAULT
}

func (m *FlowStrategyParam) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

// 端口映射状态
type PortRedirectParam struct {
	PortRedirect         []*PortRedirectParam_Item `protobuf:"bytes,10,rep,name=port_redirect,json=portRedirect,proto3" json:"port_redirect,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PortRedirectParam) Reset()         { *m = PortRedirectParam{} }
func (m *PortRedirectParam) String() string { return proto.CompactTextString(m) }
func (*PortRedirectParam) ProtoMessage()    {}
func (*PortRedirectParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{12}
}

func (m *PortRedirectParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortRedirectParam.Unmarshal(m, b)
}
func (m *PortRedirectParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortRedirectParam.Marshal(b, m, deterministic)
}
func (m *PortRedirectParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortRedirectParam.Merge(m, src)
}
func (m *PortRedirectParam) XXX_Size() int {
	return xxx_messageInfo_PortRedirectParam.Size(m)
}
func (m *PortRedirectParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PortRedirectParam.DiscardUnknown(m)
}

var xxx_messageInfo_PortRedirectParam proto.InternalMessageInfo

func (m *PortRedirectParam) GetPortRedirect() []*PortRedirectParam_Item {
	if m != nil {
		return m.PortRedirect
	}
	return nil
}

type PortRedirectParam_Item struct {
	SrcPort              string                          `protobuf:"bytes,1,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DestPort             string                          `protobuf:"bytes,2,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	DestIp               string                          `protobuf:"bytes,3,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	Switch               bool                            `protobuf:"varint,4,opt,name=switch,proto3" json:"switch,omitempty"`
	Proto                PortRedirectParam_Item_Protocol `protobuf:"varint,5,opt,name=proto,proto3,enum=PortRedirectParam_Item_Protocol" json:"proto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *PortRedirectParam_Item) Reset()         { *m = PortRedirectParam_Item{} }
func (m *PortRedirectParam_Item) String() string { return proto.CompactTextString(m) }
func (*PortRedirectParam_Item) ProtoMessage()    {}
func (*PortRedirectParam_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{12, 0}
}

func (m *PortRedirectParam_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortRedirectParam_Item.Unmarshal(m, b)
}
func (m *PortRedirectParam_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortRedirectParam_Item.Marshal(b, m, deterministic)
}
func (m *PortRedirectParam_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortRedirectParam_Item.Merge(m, src)
}
func (m *PortRedirectParam_Item) XXX_Size() int {
	return xxx_messageInfo_PortRedirectParam_Item.Size(m)
}
func (m *PortRedirectParam_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_PortRedirectParam_Item.DiscardUnknown(m)
}

var xxx_messageInfo_PortRedirectParam_Item proto.InternalMessageInfo

func (m *PortRedirectParam_Item) GetSrcPort() string {
	if m != nil {
		return m.SrcPort
	}
	return ""
}

func (m *PortRedirectParam_Item) GetDestPort() string {
	if m != nil {
		return m.DestPort
	}
	return ""
}

func (m *PortRedirectParam_Item) GetDestIp() string {
	if m != nil {
		return m.DestIp
	}
	return ""
}

func (m *PortRedirectParam_Item) GetSwitch() bool {
	if m != nil {
		return m.Switch
	}
	return false
}

func (m *PortRedirectParam_Item) GetProto() PortRedirectParam_Item_Protocol {
	if m != nil {
		return m.Proto
	}
	return PortRedirectParam_Item_UNSET
}

// 网关昵称和部署负责人信息
type DeployerParam struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	DevName              string   `protobuf:"bytes,3,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployerParam) Reset()         { *m = DeployerParam{} }
func (m *DeployerParam) String() string { return proto.CompactTextString(m) }
func (*DeployerParam) ProtoMessage()    {}
func (*DeployerParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afa8f4c35ece810, []int{13}
}

func (m *DeployerParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployerParam.Unmarshal(m, b)
}
func (m *DeployerParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployerParam.Marshal(b, m, deterministic)
}
func (m *DeployerParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployerParam.Merge(m, src)
}
func (m *DeployerParam) XXX_Size() int {
	return xxx_messageInfo_DeployerParam.Size(m)
}
func (m *DeployerParam) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployerParam.DiscardUnknown(m)
}

var xxx_messageInfo_DeployerParam proto.InternalMessageInfo

func (m *DeployerParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployerParam) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DeployerParam) GetDevName() string {
	if m != nil {
		return m.DevName
	}
	return ""
}

func init() {
	proto.RegisterEnum("FlowProtos", FlowProtos_name, FlowProtos_value)
	proto.RegisterEnum("FlowSafetype", FlowSafetype_name, FlowSafetype_value)
	proto.RegisterEnum("FlowStat", FlowStat_name, FlowStat_value)
	proto.RegisterEnum("GWResult_ActionType", GWResult_ActionType_name, GWResult_ActionType_value)
	proto.RegisterEnum("FirwareParam_Status", FirwareParam_Status_name, FirwareParam_Status_value)
	proto.RegisterEnum("GwInfoParam_Type", GwInfoParam_Type_name, GwInfoParam_Type_value)
	proto.RegisterEnum("GwInfoParam_DeployMode", GwInfoParam_DeployMode_name, GwInfoParam_DeployMode_value)
	proto.RegisterEnum("ThreatParam_Item_Type", ThreatParam_Item_Type_name, ThreatParam_Item_Type_value)
	proto.RegisterEnum("ThreatParam_Item_Status", ThreatParam_Item_Status_name, ThreatParam_Item_Status_value)
	proto.RegisterEnum("SampleParam_Status", SampleParam_Status_name, SampleParam_Status_value)
	proto.RegisterEnum("GWProtectInfoParam_Status", GWProtectInfoParam_Status_name, GWProtectInfoParam_Status_value)
	proto.RegisterEnum("StrategyParam_Type", StrategyParam_Type_name, StrategyParam_Type_value)
	proto.RegisterEnum("StrategyParam_HandleMode", StrategyParam_HandleMode_name, StrategyParam_HandleMode_value)
	proto.RegisterEnum("FlowStrategyParam_Type", FlowStrategyParam_Type_name, FlowStrategyParam_Type_value)
	proto.RegisterEnum("FlowStrategyParam_HandleMode", FlowStrategyParam_HandleMode_name, FlowStrategyParam_HandleMode_value)
	proto.RegisterEnum("PortRedirectParam_Item_Protocol", PortRedirectParam_Item_Protocol_name, PortRedirectParam_Item_Protocol_value)
	proto.RegisterType((*GWResult)(nil), "GWResult")
	proto.RegisterType((*FlowStatisticParam)(nil), "FlowStatisticParam")
	proto.RegisterType((*MonitorInfoParam)(nil), "MonitorInfoParam")
	proto.RegisterType((*MonitorInfoParam_DiskOverFlow)(nil), "MonitorInfoParam.DiskOverFlow")
	proto.RegisterType((*MonitorInfoParam_RedisInfo)(nil), "MonitorInfoParam.RedisInfo")
	proto.RegisterType((*MonitorInfoParam_VHaloNets)(nil), "MonitorInfoParam.VHaloNets")
	proto.RegisterType((*FlowParam)(nil), "FlowParam")
	proto.RegisterType((*FlowParam_FItem)(nil), "FlowParam.FItem")
	proto.RegisterType((*FirwareParam)(nil), "FirwareParam")
	proto.RegisterType((*GwInfoParam)(nil), "GwInfoParam")
	proto.RegisterType((*GwInfoParam_ModuleItem)(nil), "GwInfoParam.ModuleItem")
	proto.RegisterType((*DeviceParam)(nil), "DeviceParam")
	proto.RegisterType((*DeviceParam_Item)(nil), "DeviceParam.Item")
	proto.RegisterType((*ThreatParam)(nil), "ThreatParam")
	proto.RegisterType((*ThreatParam_Item)(nil), "ThreatParam.Item")
	proto.RegisterType((*SampleParam)(nil), "SampleParam")
	proto.RegisterType((*SampleParam_Item)(nil), "SampleParam.Item")
	proto.RegisterType((*GWProtectInfoParam)(nil), "GWProtectInfoParam")
	proto.RegisterType((*StrategyParam)(nil), "StrategyParam")
	proto.RegisterType((*FlowStrategyParam)(nil), "FlowStrategyParam")
	proto.RegisterType((*PortRedirectParam)(nil), "PortRedirectParam")
	proto.RegisterType((*PortRedirectParam_Item)(nil), "PortRedirectParam.Item")
	proto.RegisterType((*DeployerParam)(nil), "DeployerParam")
}

func init() { proto.RegisterFile("gwresult.proto", fileDescriptor_0afa8f4c35ece810) }

var fileDescriptor_0afa8f4c35ece810 = []byte{
	// 2445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x8e, 0xe3, 0x48,
	0x15, 0xde, 0x38, 0xbf, 0x3e, 0xf9, 0x19, 0xb7, 0x77, 0x76, 0x27, 0xdb, 0xbb, 0xcb, 0x8c, 0x02,
	0xcb, 0x0e, 0xb3, 0xda, 0x80, 0x1a, 0xed, 0x82, 0x66, 0x61, 0x51, 0x36, 0x71, 0xba, 0xcd, 0xa4,
	0x93, 0xa8, 0xec, 0x74, 0x98, 0x2b, 0xcb, 0x13, 0x57, 0x4f, 0xac, 0x89, 0x63, 0xcb, 0x76, 0xba,
	0xa7, 0x6f, 0xe1, 0x01, 0x90, 0x78, 0x05, 0xae, 0x91, 0x90, 0xf6, 0x1a, 0xee, 0x78, 0x03, 0x84,
	0x84, 0xb8, 0xe0, 0x11, 0x78, 0x05, 0x74, 0x4e, 0x95, 0x1d, 0x67, 0xba, 0x47, 0x70, 0x01, 0x77,
	0x75, 0xbe, 0xf3, 0x55, 0xa5, 0x7c, 0xea, 0xfc, 0x06, 0x3a, 0x2f, 0xaf, 0x63, 0x9e, 0xec, 0x36,
	0x69, 0x3f, 0x8a, 0xc3, 0x34, 0xec, 0xfd, 0x53, 0x81, 0xc6, 0xe9, 0x92, 0x11, 0xa4, 0x7f, 0x01,
	0x4d, 0x77, 0x95, 0xfa, 0xe1, 0xd6, 0x49, 0x6f, 0x22, 0xde, 0x2d, 0x3d, 0x2a, 0x3d, 0xee, 0x9c,
	0xdc, 0xef, 0x67, 0xfa, 0xfe, 0x80, 0x94, 0xf6, 0x4d, 0xc4, 0x19, 0xb8, 0xf9, 0x5a, 0xbf, 0x0f,
	0xd5, 0xc8, 0x8d, 0xdd, 0xa0, 0xab, 0x3c, 0x2a, 0x3d, 0x6e, 0x31, 0x21, 0xe8, 0x3a, 0x54, 0x4e,
	0x17, 0xe6, 0xa8, 0x5b, 0x7e, 0x54, 0x7a, 0xac, 0x32, 0x5a, 0x23, 0x73, 0x15, 0x78, 0xe6, 0xa8,
	0x5b, 0x21, 0x50, 0x08, 0xbd, 0x7f, 0x94, 0x00, 0xf6, 0x47, 0xeb, 0x4d, 0xa8, 0x8f, 0x8c, 0xf1,
	0x60, 0x31, 0xb1, 0xb5, 0x77, 0x74, 0x80, 0xda, 0xc8, 0xb8, 0x30, 0x87, 0x86, 0x56, 0xc2, 0xb5,
	0x7d, 0xc6, 0x8c, 0x81, 0xad, 0x29, 0x48, 0x3a, 0x5d, 0x3a, 0xe6, 0x74, 0x3c, 0xd3, 0xca, 0xa8,
	0xb0, 0x06, 0xe7, 0xf3, 0x89, 0xa1, 0x55, 0x50, 0x31, 0x67, 0x33, 0xdb, 0x18, 0xda, 0x5a, 0x55,
	0x6f, 0x41, 0xc3, 0xb2, 0xd9, 0xc0, 0x36, 0x4e, 0x9f, 0x6b, 0x35, 0x5d, 0x83, 0xd6, 0x7c, 0xc6,
	0x6c, 0x66, 0x8c, 0x4c, 0x86, 0xfa, 0x3a, 0xea, 0x47, 0xc6, 0x7c, 0x32, 0x7b, 0x6e, 0x30, 0xad,
	0x81, 0xd2, 0xd8, 0x64, 0xe7, 0xcb, 0x01, 0x33, 0x34, 0x95, 0xa4, 0xc9, 0x6c, 0x69, 0xd9, 0x03,
	0x5b, 0x03, 0xfd, 0x3e, 0x68, 0x42, 0x12, 0xa7, 0x11, 0xda, 0xd4, 0xef, 0x41, 0xf3, 0x7c, 0x36,
	0x35, 0xed, 0x19, 0xa3, 0x9b, 0xb4, 0xf4, 0x23, 0x68, 0x67, 0x9b, 0x4c, 0xcb, 0x36, 0x87, 0x5a,
	0xbb, 0xf7, 0xe7, 0x12, 0xe8, 0xe3, 0x4d, 0x78, 0x6d, 0xa5, 0x6e, 0xea, 0x27, 0xa9, 0xbf, 0x9a,
	0x93, 0x79, 0x3e, 0x81, 0x8e, 0xbf, 0x4d, 0x79, 0x7c, 0xe9, 0xae, 0xb8, 0xb3, 0x75, 0x03, 0x61,
	0x6e, 0x95, 0xb5, 0x73, 0x74, 0xea, 0x06, 0x5c, 0xef, 0x80, 0x12, 0xbf, 0x26, 0xc3, 0x56, 0x98,
	0x12, 0xbf, 0x46, 0x39, 0x7d, 0x4d, 0x36, 0xad, 0x30, 0x25, 0x7d, 0xad, 0x7f, 0x0c, 0x70, 0xb9,
	0x09, 0xaf, 0x9d, 0x55, 0xb8, 0xdb, 0xa6, 0x64, 0xd6, 0x36, 0x53, 0x11, 0x19, 0x22, 0xa0, 0x6b,
	0x50, 0x8e, 0x76, 0x2f, 0xba, 0x55, 0xc2, 0x71, 0xa9, 0x1f, 0x43, 0x63, 0x1b, 0xa6, 0x9b, 0x70,
	0xe5, 0x6e, 0xba, 0x35, 0x82, 0x73, 0x19, 0x9f, 0xe7, 0x7a, 0xed, 0xa7, 0xbc, 0x5b, 0x27, 0x85,
	0x10, 0x7a, 0xbf, 0xa9, 0x80, 0x76, 0x1e, 0x6e, 0xfd, 0x34, 0x8c, 0xcd, 0xed, 0x65, 0x28, 0xae,
	0xff, 0x14, 0x20, 0xe6, 0x9e, 0x9f, 0x38, 0xfe, 0xf6, 0x32, 0xa4, 0xab, 0x37, 0x4f, 0x3e, 0xec,
	0xbf, 0x49, 0xeb, 0x33, 0xe4, 0xa0, 0xc8, 0xd4, 0x38, 0x5b, 0xe2, 0xde, 0xab, 0xb5, 0xbb, 0x09,
	0xc5, 0x5e, 0xe5, 0x6d, 0x7b, 0x2f, 0xce, 0xdc, 0x4d, 0x38, 0xe5, 0x69, 0xc2, 0x54, 0xa2, 0xd3,
	0xde, 0xaf, 0x40, 0xf5, 0xfc, 0xe4, 0x95, 0xe3, 0xa7, 0x3c, 0xe8, 0x96, 0x1f, 0x95, 0x1f, 0x37,
	0x4f, 0xbe, 0x73, 0x7b, 0xeb, 0xc8, 0x4f, 0x5e, 0xcd, 0xae, 0x78, 0x8c, 0x76, 0x67, 0x0d, 0xdc,
	0x60, 0xa6, 0x3c, 0xd0, 0x1f, 0x42, 0xf3, 0xa5, 0x9b, 0xae, 0x79, 0xec, 0xa4, 0x7e, 0xc0, 0xc9,
	0x5a, 0x15, 0x06, 0x02, 0xb2, 0xfd, 0x80, 0x1f, 0xff, 0x02, 0x5a, 0xc5, 0xad, 0xe8, 0xc3, 0x91,
	0x9b, 0xae, 0xe5, 0xd3, 0xd0, 0x5a, 0xff, 0x50, 0xde, 0x20, 0x76, 0x53, 0x4e, 0x97, 0x57, 0xc4,
	0x2f, 0x30, 0x37, 0xe5, 0xc7, 0xaf, 0x40, 0xcd, 0x3f, 0x59, 0x7f, 0x1f, 0x6a, 0x18, 0x25, 0x57,
	0xe2, 0x69, 0x1b, 0x4c, 0x4a, 0xfa, 0x07, 0xd0, 0x58, 0x45, 0xbb, 0xe2, 0x01, 0xf5, 0x55, 0xb4,
	0xc3, 0xfd, 0xa8, 0x0a, 0x78, 0x20, 0x54, 0x65, 0xa1, 0x0a, 0x78, 0x40, 0x2a, 0x0d, 0xca, 0x01,
	0x0f, 0xe4, 0xa5, 0x71, 0x89, 0x3f, 0x96, 0xdb, 0xe8, 0xff, 0xfd, 0x63, 0xbd, 0x5f, 0x57, 0x40,
	0x45, 0x9b, 0x88, 0xe7, 0xff, 0x1c, 0xc8, 0xc9, 0xc4, 0x33, 0x94, 0xe8, 0x19, 0xb4, 0x7e, 0xae,
	0xee, 0x8f, 0xd1, 0xdc, 0xac, 0x81, 0x14, 0x5c, 0x1d, 0xff, 0xa5, 0x0c, 0x55, 0xc2, 0xd0, 0xa2,
	0x6b, 0x37, 0x11, 0x16, 0x6d, 0x33, 0x5a, 0xeb, 0xef, 0x41, 0x2d, 0x89, 0x57, 0x8e, 0x1f, 0xd1,
	0x05, 0xdb, 0xac, 0x9a, 0xc4, 0x2b, 0x33, 0xc2, 0xeb, 0x21, 0x1c, 0x85, 0x71, 0x4a, 0xd7, 0x6b,
	0xb3, 0x7a, 0x12, 0xaf, 0xe6, 0x61, 0x9c, 0xe2, 0x0e, 0x2f, 0x49, 0x71, 0x87, 0xf0, 0xf8, 0xaa,
	0x97, 0xa4, 0x62, 0x07, 0xc2, 0xb4, 0x43, 0xb8, 0x7c, 0xdd, 0x4b, 0x52, 0xda, 0xf1, 0x29, 0x34,
	0x28, 0xe1, 0xad, 0x42, 0xe1, 0xf6, 0x9d, 0x93, 0xa6, 0xb8, 0x2f, 0x82, 0x09, 0xcb, 0x95, 0xf8,
	0xbc, 0xe2, 0xcb, 0xd0, 0x37, 0xeb, 0xf4, 0xee, 0xe2, 0x3b, 0xf0, 0x45, 0x9f, 0x80, 0x9a, 0xb8,
	0x97, 0x5c, 0xa4, 0xc7, 0x06, 0x1d, 0xd3, 0xa6, 0x63, 0x2c, 0xf7, 0x92, 0x23, 0xc8, 0x1a, 0xa8,
	0xa7, 0x34, 0xf6, 0xa1, 0xe4, 0xd2, 0x41, 0xaa, 0x38, 0x08, 0x01, 0x3a, 0xe8, 0x63, 0x80, 0x24,
	0x75, 0xe3, 0x54, 0x38, 0x22, 0x88, 0xb0, 0x25, 0x04, 0xfd, 0x50, 0xff, 0x1e, 0x74, 0x36, 0x6e,
	0x92, 0x3a, 0x09, 0xe7, 0x5b, 0x41, 0x69, 0x12, 0xa5, 0x85, 0xa8, 0xc5, 0xf9, 0x96, 0x58, 0xdf,
	0x85, 0x76, 0x12, 0xaf, 0x4e, 0xf0, 0x93, 0x5f, 0xdc, 0xa4, 0x3c, 0xe9, 0xb6, 0xe8, 0xb9, 0x5a,
	0x12, 0xfc, 0x06, 0x31, 0x24, 0x79, 0x49, 0x7a, 0x82, 0x96, 0x14, 0xa4, 0xb6, 0x20, 0x49, 0x50,
	0x90, 0xbe, 0x2f, 0x3f, 0x3a, 0x49, 0xdd, 0xb4, 0xdb, 0xa1, 0xef, 0x52, 0xfb, 0x59, 0xd2, 0x12,
	0xdf, 0x8f, 0x2b, 0xac, 0x16, 0xad, 0xb1, 0x1f, 0x5f, 0xbb, 0x31, 0x17, 0x7e, 0xd0, 0x85, 0xfa,
	0x15, 0x8f, 0x13, 0x3f, 0xdc, 0xca, 0x18, 0xc9, 0x44, 0xfd, 0x33, 0x38, 0xda, 0x45, 0x2f, 0x63,
	0xd7, 0xe3, 0xf4, 0x01, 0x49, 0xea, 0x06, 0xd9, 0xfb, 0x6a, 0x52, 0x61, 0x67, 0xb8, 0xfe, 0x15,
	0x74, 0x32, 0x32, 0x5e, 0x61, 0x97, 0xd0, 0x83, 0x63, 0xed, 0x29, 0xfe, 0x5a, 0xdf, 0x22, 0x1d,
	0x6b, 0x4b, 0xae, 0x10, 0xf1, 0x0e, 0xf8, 0x0b, 0xe1, 0x2e, 0xcb, 0x7f, 0x99, 0xd8, 0xfb, 0x63,
	0x09, 0x6a, 0x92, 0x74, 0x50, 0x54, 0xda, 0xa0, 0x2e, 0xe6, 0xa7, 0x6c, 0x30, 0x32, 0xa7, 0xa7,
	0x5a, 0x49, 0x7f, 0x17, 0xee, 0x8d, 0x4d, 0x86, 0x69, 0xdf, 0x31, 0xa7, 0x17, 0x83, 0x89, 0x39,
	0xd2, 0x14, 0x4c, 0xed, 0x0b, 0x36, 0xc9, 0x81, 0x32, 0x56, 0x8f, 0xd1, 0x6c, 0x39, 0x9d, 0xcc,
	0x06, 0x23, 0x07, 0xf7, 0x55, 0xf4, 0xf7, 0xe0, 0x28, 0x47, 0xc6, 0xe6, 0xd4, 0xb4, 0xce, 0x8c,
	0x91, 0x56, 0xc5, 0x1a, 0xb0, 0x87, 0x07, 0xe6, 0x44, 0xab, 0xe1, 0xaf, 0x9f, 0x8f, 0xbe, 0x70,
	0x0c, 0xc6, 0x44, 0xd1, 0x19, 0x9e, 0x19, 0xc3, 0x67, 0xce, 0xec, 0x99, 0xd6, 0xc0, 0xbb, 0x18,
	0xbf, 0x32, 0x86, 0x82, 0xa9, 0xf6, 0xfe, 0x54, 0x85, 0xe6, 0xe9, 0xf5, 0x3e, 0xcf, 0xbe, 0xdd,
	0xc0, 0x87, 0x2e, 0xa4, 0xbc, 0xe9, 0x42, 0x3f, 0x00, 0xed, 0xd2, 0x8f, 0x03, 0x34, 0x9e, 0x93,
	0x9d, 0x20, 0x4a, 0xf1, 0xbd, 0x0c, 0xbf, 0x90, 0x27, 0x7d, 0x02, 0x9d, 0xb5, 0x1b, 0x7b, 0x44,
	0x0d, 0x42, 0x8f, 0x6f, 0x64, 0x79, 0x6e, 0x67, 0xe8, 0x39, 0x82, 0xfa, 0x0f, 0xa1, 0x16, 0x84,
	0xde, 0x6e, 0xc3, 0xbb, 0x55, 0x0a, 0xf8, 0x07, 0xfd, 0xc2, 0x45, 0xfb, 0xe7, 0xa4, 0xa2, 0xb8,
	0x97, 0x34, 0x8a, 0x80, 0x5d, 0x14, 0x6d, 0x6e, 0x1c, 0xdf, 0xa3, 0xa0, 0xc3, 0x08, 0x20, 0xc0,
	0xf4, 0xf4, 0x47, 0xd0, 0xda, 0x45, 0x4e, 0x1c, 0xee, 0x52, 0x1e, 0x63, 0x20, 0x8b, 0x50, 0x83,
	0x5d, 0xc4, 0x08, 0x32, 0x23, 0x2c, 0x75, 0x7e, 0x44, 0x51, 0xa6, 0x32, 0xc5, 0x8f, 0xf4, 0x4f,
	0xa0, 0x42, 0x71, 0xa7, 0x92, 0x6b, 0x1c, 0x1d, 0xfc, 0x3a, 0xf5, 0x24, 0xa4, 0xa6, 0xd4, 0xe5,
	0xae, 0x28, 0xa6, 0x54, 0x86, 0x4b, 0xfd, 0x23, 0x50, 0xf7, 0x2e, 0x28, 0x02, 0x69, 0x0f, 0xa0,
	0x1d, 0xd7, 0x2f, 0x9c, 0xcc, 0x83, 0x30, 0x84, 0xaa, 0x4c, 0x5d, 0xbf, 0xb0, 0x05, 0xa0, 0xff,
	0x14, 0x9a, 0x1e, 0x8f, 0x36, 0xe1, 0x0d, 0x99, 0x86, 0xa2, 0xa7, 0xf3, 0xc6, 0xa7, 0x8f, 0x48,
	0x8f, 0x46, 0x62, 0xe0, 0xe5, 0x6b, 0xfd, 0x73, 0x78, 0x57, 0x64, 0x12, 0x6f, 0x23, 0x62, 0xc0,
	0x49, 0x36, 0xa1, 0x08, 0xaf, 0x36, 0xd3, 0x28, 0xa7, 0x78, 0x1b, 0x0a, 0x02, 0x6b, 0x13, 0xa6,
	0xc7, 0x4f, 0x01, 0xf6, 0x36, 0xc4, 0x3c, 0x59, 0x68, 0x0a, 0x68, 0x5d, 0xf4, 0x05, 0xe5, 0xc0,
	0x17, 0x7a, 0x23, 0xa8, 0xdc, 0xd9, 0x3a, 0x5d, 0x58, 0xe7, 0x03, 0x66, 0x6b, 0x25, 0x5d, 0x85,
	0xea, 0xc5, 0xd9, 0x60, 0x32, 0xd3, 0x14, 0x5a, 0x2e, 0xcd, 0xb1, 0xa9, 0x95, 0xd1, 0xf7, 0x2e,
	0x8c, 0xe9, 0xc2, 0x22, 0x4d, 0xa5, 0xf7, 0x0d, 0xc0, 0xfe, 0x53, 0xc8, 0xbb, 0xa9, 0x37, 0x3a,
	0x9f, 0x8d, 0x8c, 0x83, 0xd8, 0x61, 0xb3, 0x85, 0x6d, 0x20, 0xaa, 0x95, 0xf4, 0x0e, 0x80, 0xb5,
	0x34, 0xed, 0xe1, 0x19, 0xc9, 0x4a, 0xef, 0x6f, 0x0a, 0x34, 0x47, 0xfc, 0xca, 0x5f, 0xc9, 0x04,
	0x71, 0x82, 0xe6, 0x43, 0xb1, 0x58, 0x2a, 0x8e, 0xfa, 0x05, 0x4a, 0x9f, 0x7c, 0x06, 0x04, 0x8b,
	0xaa, 0xc5, 0xef, 0x14, 0xa8, 0x90, 0x11, 0x84, 0x07, 0x94, 0x72, 0x0f, 0x90, 0x4f, 0xab, 0xec,
	0x9f, 0x36, 0x33, 0x53, 0xb9, 0x60, 0x26, 0x7c, 0x6e, 0x4c, 0x0f, 0x81, 0x1b, 0xbf, 0x92, 0x9e,
	0xbc, 0x07, 0xd0, 0x29, 0xfd, 0xc4, 0x09, 0xb7, 0x1b, 0x7f, 0xcb, 0xa9, 0x48, 0x34, 0x58, 0xc3,
	0x4f, 0x66, 0x24, 0x63, 0x83, 0x40, 0x79, 0x57, 0xaa, 0x45, 0x7f, 0x04, 0x08, 0x49, 0xc2, 0xa7,
	0x70, 0x8f, 0xfa, 0xb3, 0x2d, 0x4f, 0x9d, 0xe4, 0xda, 0x4f, 0x57, 0x6b, 0x72, 0xdc, 0x06, 0xeb,
	0x64, 0xb0, 0x45, 0x28, 0xc6, 0x14, 0x96, 0x14, 0xbe, 0xca, 0x79, 0x0d, 0xe2, 0xb5, 0x25, 0x2a,
	0x69, 0x8f, 0x41, 0xdb, 0xb8, 0x5b, 0xe7, 0xca, 0x4f, 0xfc, 0x9c, 0xa8, 0x8a, 0x03, 0x37, 0xee,
	0xf6, 0x02, 0x61, 0xc1, 0xec, 0x7d, 0x5b, 0x81, 0xa6, 0xbd, 0x8e, 0xb9, 0x9b, 0xe6, 0x86, 0x4d,
	0x49, 0x3c, 0x34, 0x6c, 0x81, 0x22, 0x0d, 0x2b, 0x58, 0x64, 0xd8, 0x7f, 0x95, 0xa5, 0x61, 0x1f,
	0x00, 0x96, 0x52, 0x07, 0x8d, 0x29, 0xac, 0x8b, 0x05, 0xf8, 0xdc, 0x5d, 0xe9, 0x3f, 0xc9, 0x4f,
	0xa5, 0x50, 0x53, 0xc8, 0xdb, 0xdf, 0xbf, 0x75, 0xaa, 0x88, 0x37, 0x79, 0x34, 0x79, 0x5e, 0x17,
	0xea, 0xab, 0x70, 0x9b, 0xf2, 0x6d, 0x2a, 0xdf, 0x22, 0x13, 0xf5, 0x9f, 0x43, 0x5b, 0x1e, 0x29,
	0x53, 0x7b, 0x85, 0x0e, 0xed, 0xde, 0x3e, 0x54, 0xa6, 0xf7, 0x96, 0xa0, 0xcb, 0xc4, 0xfd, 0x10,
	0x9a, 0x6e, 0x9a, 0xba, 0x2b, 0x99, 0xe7, 0x44, 0x59, 0x07, 0x01, 0x51, 0xa2, 0xdb, 0x77, 0x0f,
	0x22, 0xc5, 0xc8, 0xee, 0x61, 0xdf, 0x22, 0x88, 0xcc, 0x22, 0x5a, 0x04, 0x2c, 0x09, 0x77, 0x84,
	0x4a, 0x03, 0x2a, 0x96, 0x69, 0xa3, 0x3f, 0xd7, 0x40, 0x31, 0xe7, 0x9a, 0x82, 0x6e, 0x3e, 0x9a,
	0x5a, 0x67, 0xe6, 0x2f, 0x07, 0xc3, 0x67, 0x5a, 0x59, 0xd7, 0xa1, 0xb3, 0x10, 0x73, 0xc8, 0xf2,
	0xcc, 0xb4, 0x0d, 0x73, 0xae, 0x55, 0x70, 0x24, 0x28, 0x62, 0x74, 0x40, 0xb5, 0xc0, 0xfc, 0x66,
	0x32, 0x18, 0x3e, 0x33, 0xe7, 0x5a, 0xad, 0xc0, 0x24, 0x8c, 0x98, 0x75, 0x2c, 0x28, 0x93, 0xc1,
	0xd4, 0x9c, 0xda, 0x6c, 0x61, 0x99, 0xb3, 0xa9, 0xd6, 0xc8, 0x78, 0x07, 0xa8, 0xda, 0x7b, 0x5a,
	0x2c, 0x62, 0x8b, 0xe9, 0xb3, 0xe9, 0x6c, 0x39, 0xd5, 0xde, 0xc1, 0x38, 0x1e, 0xcf, 0x16, 0xd3,
	0x91, 0x56, 0x12, 0x33, 0x8f, 0x71, 0x61, 0x4c, 0xe5, 0x64, 0xb4, 0x1c, 0xb0, 0x29, 0x96, 0xa8,
	0x72, 0xef, 0xf7, 0x65, 0x68, 0x5a, 0x6e, 0x10, 0x6d, 0x64, 0x38, 0x62, 0x44, 0x79, 0x79, 0x44,
	0x79, 0xff, 0xa9, 0x88, 0x3c, 0x84, 0x26, 0x25, 0xae, 0x98, 0x07, 0xae, 0xbf, 0x95, 0x5d, 0x18,
	0x20, 0xc4, 0x08, 0xd1, 0x3f, 0x83, 0xda, 0xc1, 0xab, 0xbe, 0xdb, 0x2f, 0xfc, 0x5a, 0xf6, 0xa0,
	0x92, 0x82, 0x2e, 0x9b, 0x90, 0x56, 0xb8, 0x6c, 0x55, 0xba, 0x6c, 0x71, 0x87, 0x70, 0x59, 0xc1,
	0x22, 0x4f, 0x2d, 0x14, 0xf7, 0xda, 0x41, 0x71, 0x3f, 0x7e, 0xbd, 0x4f, 0x12, 0x49, 0x20, 0xdf,
	0x5e, 0x49, 0x02, 0x4c, 0x12, 0x49, 0xfe, 0xea, 0xb8, 0x24, 0x86, 0x28, 0x24, 0x6d, 0xa6, 0x24,
	0x94, 0x46, 0x3c, 0x3f, 0x92, 0x3d, 0x19, 0x2e, 0x91, 0xe1, 0x45, 0xb2, 0x0d, 0x53, 0xbc, 0x48,
	0x6f, 0x41, 0x69, 0x47, 0xa5, 0x40, 0x65, 0xa5, 0x1d, 0xcd, 0x5c, 0x01, 0x65, 0x7e, 0x95, 0x29,
	0x69, 0xd0, 0x9b, 0xe5, 0x0f, 0x72, 0x04, 0x6d, 0x1c, 0xf5, 0x16, 0xd6, 0xde, 0x95, 0x3a, 0x00,
	0xc3, 0xd9, 0x64, 0x62, 0x0c, 0x6d, 0xd1, 0x5c, 0xec, 0x65, 0xac, 0xf7, 0x0a, 0xfa, 0x47, 0x26,
	0x63, 0xc9, 0x37, 0x46, 0x5a, 0xb9, 0xf7, 0xdb, 0x12, 0xe8, 0xa7, 0xcb, 0xb9, 0xc8, 0x0c, 0xfb,
	0xda, 0x3f, 0x28, 0xe4, 0x10, 0x61, 0x64, 0x31, 0x91, 0x1f, 0xf7, 0x6f, 0x93, 0xf3, 0xde, 0x28,
	0xcb, 0x2f, 0x24, 0xf6, 0xbe, 0xbc, 0xbb, 0x01, 0xea, 0x00, 0xc8, 0x21, 0x59, 0x5c, 0x12, 0x9b,
	0x9d, 0xa9, 0x44, 0x8c, 0x91, 0xa6, 0xf4, 0xbe, 0x55, 0xa0, 0x6d, 0xa5, 0x38, 0x19, 0xbc, 0xbc,
	0x11, 0x97, 0x79, 0x08, 0xcd, 0x44, 0x02, 0x4e, 0xee, 0x42, 0x90, 0x41, 0xa6, 0xa7, 0x3f, 0x85,
	0xe6, 0xda, 0xdd, 0x62, 0xad, 0xa3, 0x42, 0x29, 0x52, 0xc7, 0x07, 0xfd, 0x83, 0x53, 0xfa, 0x67,
	0xc4, 0x10, 0xa5, 0x72, 0x9d, 0xaf, 0xf5, 0x2f, 0xa1, 0xe5, 0xf1, 0x4b, 0xbe, 0x4d, 0x64, 0x6b,
	0x5d, 0xce, 0x9c, 0xe9, 0x60, 0x33, 0x25, 0x9d, 0xa6, 0x24, 0x52, 0x10, 0xbf, 0x0f, 0x35, 0xbe,
	0x75, 0x5f, 0x6c, 0xc4, 0x2c, 0xd7, 0x60, 0x52, 0xea, 0x7d, 0x21, 0x83, 0xfc, 0x1e, 0x34, 0xed,
	0xe7, 0xf3, 0xc3, 0xea, 0x45, 0xc1, 0x2a, 0xab, 0x57, 0x1b, 0x54, 0x8a, 0x48, 0x59, 0xbc, 0xbe,
	0x06, 0xd8, 0x5f, 0x50, 0x0c, 0xf7, 0xc5, 0xd2, 0xa7, 0x43, 0x47, 0x86, 0x59, 0x16, 0x60, 0xa5,
	0x62, 0xb4, 0x29, 0xbd, 0xbf, 0x2a, 0x70, 0x24, 0xba, 0xe6, 0xa2, 0xe5, 0x1e, 0x83, 0x26, 0x9b,
	0xeb, 0x37, 0xcd, 0xd7, 0xb9, 0x2c, 0x90, 0x4d, 0x4f, 0xff, 0xfa, 0x2e, 0x13, 0x7e, 0xdc, 0xbf,
	0x75, 0xe4, 0xdb, 0xcc, 0xf8, 0xf4, 0x4e, 0x33, 0x3e, 0xb8, 0xe3, 0x80, 0xff, 0xde, 0x94, 0x03,
	0x69, 0x4a, 0x6c, 0x92, 0x27, 0xcb, 0xd9, 0xa1, 0x39, 0xe9, 0xef, 0x8e, 0xe5, 0xac, 0x68, 0x52,
	0x09, 0xfd, 0x2f, 0xcd, 0xfa, 0x07, 0x05, 0x8e, 0x70, 0x88, 0xc3, 0xc9, 0x3a, 0xe6, 0x2b, 0x59,
	0x00, 0x7f, 0x06, 0x6d, 0x1c, 0xf4, 0x9c, 0x58, 0xa2, 0x5d, 0x90, 0x5d, 0xe9, 0x2d, 0xaa, 0xc8,
	0x2a, 0xad, 0xa8, 0x80, 0x1f, 0xff, 0xbd, 0x24, 0xd3, 0x47, 0x71, 0xca, 0x94, 0x1d, 0x76, 0x36,
	0x65, 0xe2, 0xa4, 0xcf, 0xb3, 0x79, 0x52, 0x34, 0x1d, 0x0d, 0x04, 0x48, 0xf9, 0x00, 0xea, 0xa4,
	0xf4, 0x23, 0x59, 0xf0, 0x6a, 0x28, 0x9a, 0x11, 0x1a, 0x52, 0x16, 0x72, 0x69, 0x48, 0x21, 0xe9,
	0x5f, 0x42, 0x95, 0x86, 0x4c, 0x2a, 0x61, 0x9d, 0x93, 0x47, 0x6f, 0xb9, 0x67, 0x7f, 0x2e, 0x27,
	0x51, 0x26, 0xe8, 0xbd, 0x1f, 0x41, 0x23, 0x83, 0x30, 0xe7, 0x2f, 0xa6, 0x96, 0x81, 0x56, 0xab,
	0x43, 0x79, 0x31, 0x9a, 0x6b, 0x25, 0x5c, 0xd8, 0x43, 0x2c, 0x59, 0x75, 0x28, 0x0f, 0x26, 0x13,
	0xad, 0xdc, 0xb3, 0xa1, 0x2d, 0xfa, 0x38, 0x1e, 0xcf, 0xb3, 0xbf, 0xe2, 0x6e, 0x35, 0x93, 0xf7,
	0xa1, 0x1a, 0xad, 0xc3, 0x2d, 0x97, 0x1f, 0x26, 0x04, 0x9a, 0xa0, 0xf9, 0x95, 0x53, 0xe8, 0xa9,
	0xea, 0x1e, 0xbf, 0x9a, 0xba, 0x01, 0x7f, 0xf2, 0x11, 0xc0, 0x7e, 0x60, 0xc6, 0x0c, 0x32, 0x9e,
	0x3b, 0x79, 0x35, 0x7a, 0xe2, 0x43, 0xab, 0x38, 0x07, 0xd3, 0xbf, 0x67, 0x96, 0x93, 0x5d, 0xb6,
	0x09, 0xf5, 0xb1, 0xe5, 0x58, 0x83, 0xb1, 0x6c, 0x19, 0xc7, 0x96, 0x93, 0x3f, 0x2f, 0x06, 0xe1,
	0xd8, 0x72, 0x46, 0x83, 0xe9, 0xa9, 0xc1, 0xb4, 0xb2, 0x54, 0x2f, 0xa6, 0x34, 0x23, 0x69, 0x15,
	0xf4, 0x97, 0xb1, 0xe5, 0x90, 0x84, 0xfc, 0xea, 0x93, 0x53, 0x68, 0x64, 0xa3, 0xa9, 0xd8, 0x6b,
	0xe7, 0xbf, 0x43, 0x7b, 0x6d, 0x67, 0x30, 0xb4, 0xcd, 0x8b, 0xfc, 0xa7, 0x6c, 0x39, 0x9c, 0x69,
	0x8a, 0xb8, 0x95, 0xed, 0x98, 0xa3, 0x89, 0xa1, 0x95, 0x5f, 0xd4, 0xc8, 0xc0, 0x3f, 0xfe, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x3b, 0xb8, 0xc5, 0x14, 0x15, 0x00, 0x00,
}
