// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scommand.proto

package scommand

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command_TaskType int32

const (
	Command_DEFAULT_TASKTYPE Command_TaskType = 0
	Command_GW_SET           Command_TaskType = 1
	Command_DEVICE_SET       Command_TaskType = 2
	Command_STRATEGY_ADD     Command_TaskType = 3
	Command_STRATEGY_SET     Command_TaskType = 4
	Command_SAMPLE_SET       Command_TaskType = 5
	Command_PORTREDIRECT_SET Command_TaskType = 6
	Command_STATUS_UPDATE    Command_TaskType = 7
	Command_DEPLOYER_SET     Command_TaskType = 8
	Command_FIRMWARE_UPGRADE Command_TaskType = 9
)

var Command_TaskType_name = map[int32]string{
	0: "DEFAULT_TASKTYPE",
	1: "GW_SET",
	2: "DEVICE_SET",
	3: "STRATEGY_ADD",
	4: "STRATEGY_SET",
	5: "SAMPLE_SET",
	6: "PORTREDIRECT_SET",
	7: "STATUS_UPDATE",
	8: "DEPLOYER_SET",
	9: "FIRMWARE_UPGRADE",
}

var Command_TaskType_value = map[string]int32{
	"DEFAULT_TASKTYPE": 0,
	"GW_SET":           1,
	"DEVICE_SET":       2,
	"STRATEGY_ADD":     3,
	"STRATEGY_SET":     4,
	"SAMPLE_SET":       5,
	"PORTREDIRECT_SET": 6,
	"STATUS_UPDATE":    7,
	"DEPLOYER_SET":     8,
	"FIRMWARE_UPGRADE": 9,
}

func (x Command_TaskType) String() string {
	return proto.EnumName(Command_TaskType_name, int32(x))
}

func (Command_TaskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{0, 0}
}

type StatusUpdateParam_Type int32

const (
	StatusUpdateParam_DEFAULT_INFO StatusUpdateParam_Type = 0
	StatusUpdateParam_GWINFO       StatusUpdateParam_Type = 1
	StatusUpdateParam_DEVICE       StatusUpdateParam_Type = 2
	StatusUpdateParam_GWPROTECT    StatusUpdateParam_Type = 3
	StatusUpdateParam_STRATEGY     StatusUpdateParam_Type = 4
	StatusUpdateParam_PORTREDIRECT StatusUpdateParam_Type = 5
	StatusUpdateParam_DEPLOYER     StatusUpdateParam_Type = 6
)

var StatusUpdateParam_Type_name = map[int32]string{
	0: "DEFAULT_INFO",
	1: "GWINFO",
	2: "DEVICE",
	3: "GWPROTECT",
	4: "STRATEGY",
	5: "PORTREDIRECT",
	6: "DEPLOYER",
}

var StatusUpdateParam_Type_value = map[string]int32{
	"DEFAULT_INFO": 0,
	"GWINFO":       1,
	"DEVICE":       2,
	"GWPROTECT":    3,
	"STRATEGY":     4,
	"PORTREDIRECT": 5,
	"DEPLOYER":     6,
}

func (x StatusUpdateParam_Type) String() string {
	return proto.EnumName(StatusUpdateParam_Type_name, int32(x))
}

func (StatusUpdateParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{2, 0}
}

type GwSetParam_Type int32

const (
	GwSetParam_DEFAULT GwSetParam_Type = 0
	GwSetParam_PROTECT GwSetParam_Type = 1
	GwSetParam_RESTART GwSetParam_Type = 2
)

var GwSetParam_Type_name = map[int32]string{
	0: "DEFAULT",
	1: "PROTECT",
	2: "RESTART",
}

var GwSetParam_Type_value = map[string]int32{
	"DEFAULT": 0,
	"PROTECT": 1,
	"RESTART": 2,
}

func (x GwSetParam_Type) String() string {
	return proto.EnumName(GwSetParam_Type_name, int32(x))
}

func (GwSetParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{3, 0}
}

type DeviceSetParam_Type int32

const (
	DeviceSetParam_DEFAULT             DeviceSetParam_Type = 0
	DeviceSetParam_PROTECT             DeviceSetParam_Type = 1
	DeviceSetParam_INTERNET            DeviceSetParam_Type = 2
	DeviceSetParam_GUEST_ACCESS_DEVICE DeviceSetParam_Type = 3
	DeviceSetParam_LANVISIT            DeviceSetParam_Type = 4
)

var DeviceSetParam_Type_name = map[int32]string{
	0: "DEFAULT",
	1: "PROTECT",
	2: "INTERNET",
	3: "GUEST_ACCESS_DEVICE",
	4: "LANVISIT",
}

var DeviceSetParam_Type_value = map[string]int32{
	"DEFAULT":             0,
	"PROTECT":             1,
	"INTERNET":            2,
	"GUEST_ACCESS_DEVICE": 3,
	"LANVISIT":            4,
}

func (x DeviceSetParam_Type) String() string {
	return proto.EnumName(DeviceSetParam_Type_name, int32(x))
}

func (DeviceSetParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{4, 0}
}

type StrategyAddParam_Type int32

const (
	StrategyAddParam_TYPEDEFAULT StrategyAddParam_Type = 0
	StrategyAddParam_WHITEMODE   StrategyAddParam_Type = 1
	StrategyAddParam_BLACKMODE   StrategyAddParam_Type = 2
)

var StrategyAddParam_Type_name = map[int32]string{
	0: "TYPEDEFAULT",
	1: "WHITEMODE",
	2: "BLACKMODE",
}

var StrategyAddParam_Type_value = map[string]int32{
	"TYPEDEFAULT": 0,
	"WHITEMODE":   1,
	"BLACKMODE":   2,
}

func (x StrategyAddParam_Type) String() string {
	return proto.EnumName(StrategyAddParam_Type_name, int32(x))
}

func (StrategyAddParam_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{5, 0}
}

type StrategyAddParam_HandleMode int32

const (
	StrategyAddParam_MODEDEFAULT    StrategyAddParam_HandleMode = 0
	StrategyAddParam_PREVENTWARNING StrategyAddParam_HandleMode = 1
	StrategyAddParam_WARNING        StrategyAddParam_HandleMode = 2
)

var StrategyAddParam_HandleMode_name = map[int32]string{
	0: "MODEDEFAULT",
	1: "PREVENTWARNING",
	2: "WARNING",
}

var StrategyAddParam_HandleMode_value = map[string]int32{
	"MODEDEFAULT":    0,
	"PREVENTWARNING": 1,
	"WARNING":        2,
}

func (x StrategyAddParam_HandleMode) String() string {
	return proto.EnumName(StrategyAddParam_HandleMode_name, int32(x))
}

func (StrategyAddParam_HandleMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{5, 1}
}

type StrategySetParam_HandleMode int32

const (
	StrategySetParam_MODEDEFAULT    StrategySetParam_HandleMode = 0
	StrategySetParam_PREVENTWARNING StrategySetParam_HandleMode = 1
	StrategySetParam_WARNING        StrategySetParam_HandleMode = 2
)

var StrategySetParam_HandleMode_name = map[int32]string{
	0: "MODEDEFAULT",
	1: "PREVENTWARNING",
	2: "WARNING",
}

var StrategySetParam_HandleMode_value = map[string]int32{
	"MODEDEFAULT":    0,
	"PREVENTWARNING": 1,
	"WARNING":        2,
}

func (x StrategySetParam_HandleMode) String() string {
	return proto.EnumName(StrategySetParam_HandleMode_name, int32(x))
}

func (StrategySetParam_HandleMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{6, 0}
}

type PortRedirectSetParam_Protocol int32

const (
	PortRedirectSetParam_UNSET PortRedirectSetParam_Protocol = 0
	PortRedirectSetParam_UDP   PortRedirectSetParam_Protocol = 1
	PortRedirectSetParam_TCP   PortRedirectSetParam_Protocol = 2
	PortRedirectSetParam_ALL   PortRedirectSetParam_Protocol = 3
)

var PortRedirectSetParam_Protocol_name = map[int32]string{
	0: "UNSET",
	1: "UDP",
	2: "TCP",
	3: "ALL",
}

var PortRedirectSetParam_Protocol_value = map[string]int32{
	"UNSET": 0,
	"UDP":   1,
	"TCP":   2,
	"ALL":   3,
}

func (x PortRedirectSetParam_Protocol) String() string {
	return proto.EnumName(PortRedirectSetParam_Protocol_name, int32(x))
}

func (PortRedirectSetParam_Protocol) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{8, 0}
}

//基础最外层命令
type Command struct {
	ItemType             Command_TaskType `protobuf:"varint,1,opt,name=item_type,json=itemType,proto3,enum=Command_TaskType" json:"item_type,omitempty"`
	Param                []byte           `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	CmdID                string           `protobuf:"bytes,3,opt,name=cmdID,proto3" json:"cmdID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{0}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetItemType() Command_TaskType {
	if m != nil {
		return m.ItemType
	}
	return Command_DEFAULT_TASKTYPE
}

func (m *Command) GetParam() []byte {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *Command) GetCmdID() string {
	if m != nil {
		return m.CmdID
	}
	return ""
}

type FirmwareUpgradeParam struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	SOCType              string   `protobuf:"bytes,4,opt,name=SOC_type,json=SOCType,proto3" json:"SOC_type,omitempty"`
	BoardName            string   `protobuf:"bytes,5,opt,name=board_name,json=boardName,proto3" json:"board_name,omitempty"`
	FirmwareType         string   `protobuf:"bytes,6,opt,name=firmware_type,json=firmwareType,proto3" json:"firmware_type,omitempty"`
	FirmwareName         string   `protobuf:"bytes,7,opt,name=firmware_name,json=firmwareName,proto3" json:"firmware_name,omitempty"`
	Md5                  string   `protobuf:"bytes,8,opt,name=md5,proto3" json:"md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirmwareUpgradeParam) Reset()         { *m = FirmwareUpgradeParam{} }
func (m *FirmwareUpgradeParam) String() string { return proto.CompactTextString(m) }
func (*FirmwareUpgradeParam) ProtoMessage()    {}
func (*FirmwareUpgradeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{1}
}

func (m *FirmwareUpgradeParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirmwareUpgradeParam.Unmarshal(m, b)
}
func (m *FirmwareUpgradeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirmwareUpgradeParam.Marshal(b, m, deterministic)
}
func (m *FirmwareUpgradeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirmwareUpgradeParam.Merge(m, src)
}
func (m *FirmwareUpgradeParam) XXX_Size() int {
	return xxx_messageInfo_FirmwareUpgradeParam.Size(m)
}
func (m *FirmwareUpgradeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_FirmwareUpgradeParam.DiscardUnknown(m)
}

var xxx_messageInfo_FirmwareUpgradeParam proto.InternalMessageInfo

func (m *FirmwareUpgradeParam) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *FirmwareUpgradeParam) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FirmwareUpgradeParam) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *FirmwareUpgradeParam) GetSOCType() string {
	if m != nil {
		return m.SOCType
	}
	return ""
}

func (m *FirmwareUpgradeParam) GetBoardName() string {
	if m != nil {
		return m.BoardName
	}
	return ""
}

func (m *FirmwareUpgradeParam) GetFirmwareType() string {
	if m != nil {
		return m.FirmwareType
	}
	return ""
}

func (m *FirmwareUpgradeParam) GetFirmwareName() string {
	if m != nil {
		return m.FirmwareName
	}
	return ""
}

func (m *FirmwareUpgradeParam) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

//更新小V基本信息
type StatusUpdateParam struct {
	Type                 StatusUpdateParam_Type `protobuf:"varint,1,opt,name=type,proto3,enum=StatusUpdateParam_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StatusUpdateParam) Reset()         { *m = StatusUpdateParam{} }
func (m *StatusUpdateParam) String() string { return proto.CompactTextString(m) }
func (*StatusUpdateParam) ProtoMessage()    {}
func (*StatusUpdateParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{2}
}

func (m *StatusUpdateParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusUpdateParam.Unmarshal(m, b)
}
func (m *StatusUpdateParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusUpdateParam.Marshal(b, m, deterministic)
}
func (m *StatusUpdateParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusUpdateParam.Merge(m, src)
}
func (m *StatusUpdateParam) XXX_Size() int {
	return xxx_messageInfo_StatusUpdateParam.Size(m)
}
func (m *StatusUpdateParam) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusUpdateParam.DiscardUnknown(m)
}

var xxx_messageInfo_StatusUpdateParam proto.InternalMessageInfo

func (m *StatusUpdateParam) GetType() StatusUpdateParam_Type {
	if m != nil {
		return m.Type
	}
	return StatusUpdateParam_DEFAULT_INFO
}

//小v设置
type GwSetParam struct {
	Type                 GwSetParam_Type `protobuf:"varint,1,opt,name=type,proto3,enum=GwSetParam_Type" json:"type,omitempty"`
	Switch               bool            `protobuf:"varint,2,opt,name=switch,proto3" json:"switch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GwSetParam) Reset()         { *m = GwSetParam{} }
func (m *GwSetParam) String() string { return proto.CompactTextString(m) }
func (*GwSetParam) ProtoMessage()    {}
func (*GwSetParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{3}
}

func (m *GwSetParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GwSetParam.Unmarshal(m, b)
}
func (m *GwSetParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GwSetParam.Marshal(b, m, deterministic)
}
func (m *GwSetParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GwSetParam.Merge(m, src)
}
func (m *GwSetParam) XXX_Size() int {
	return xxx_messageInfo_GwSetParam.Size(m)
}
func (m *GwSetParam) XXX_DiscardUnknown() {
	xxx_messageInfo_GwSetParam.DiscardUnknown(m)
}

var xxx_messageInfo_GwSetParam proto.InternalMessageInfo

func (m *GwSetParam) GetType() GwSetParam_Type {
	if m != nil {
		return m.Type
	}
	return GwSetParam_DEFAULT
}

func (m *GwSetParam) GetSwitch() bool {
	if m != nil {
		return m.Switch
	}
	return false
}

//设备设置
type DeviceSetParam struct {
	DeviceMac            string              `protobuf:"bytes,1,opt,name=device_mac,json=deviceMac,proto3" json:"device_mac,omitempty"`
	Type                 DeviceSetParam_Type `protobuf:"varint,2,opt,name=type,proto3,enum=DeviceSetParam_Type" json:"type,omitempty"`
	Switch               bool                `protobuf:"varint,3,opt,name=switch,proto3" json:"switch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *DeviceSetParam) Reset()         { *m = DeviceSetParam{} }
func (m *DeviceSetParam) String() string { return proto.CompactTextString(m) }
func (*DeviceSetParam) ProtoMessage()    {}
func (*DeviceSetParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{4}
}

func (m *DeviceSetParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSetParam.Unmarshal(m, b)
}
func (m *DeviceSetParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSetParam.Marshal(b, m, deterministic)
}
func (m *DeviceSetParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSetParam.Merge(m, src)
}
func (m *DeviceSetParam) XXX_Size() int {
	return xxx_messageInfo_DeviceSetParam.Size(m)
}
func (m *DeviceSetParam) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSetParam.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSetParam proto.InternalMessageInfo

func (m *DeviceSetParam) GetDeviceMac() string {
	if m != nil {
		return m.DeviceMac
	}
	return ""
}

func (m *DeviceSetParam) GetType() DeviceSetParam_Type {
	if m != nil {
		return m.Type
	}
	return DeviceSetParam_DEFAULT
}

func (m *DeviceSetParam) GetSwitch() bool {
	if m != nil {
		return m.Switch
	}
	return false
}

//策略添加
type StrategyAddParam struct {
	StrategyId           string                      `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	HandleMode           StrategyAddParam_HandleMode `protobuf:"varint,2,opt,name=handle_mode,json=handleMode,proto3,enum=StrategyAddParam_HandleMode" json:"handle_mode,omitempty"`
	DefenseType          StrategyAddParam_Type       `protobuf:"varint,3,opt,name=defense_type,json=defenseType,proto3,enum=StrategyAddParam_Type" json:"defense_type,omitempty"`
	DIPList              []string                    `protobuf:"bytes,5,rep,name=dIP_list,json=dIPList,proto3" json:"dIP_list,omitempty"`
	URLList              []string                    `protobuf:"bytes,6,rep,name=URL_list,json=URLList,proto3" json:"URL_list,omitempty"`
	Enable               bool                        `protobuf:"varint,7,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *StrategyAddParam) Reset()         { *m = StrategyAddParam{} }
func (m *StrategyAddParam) String() string { return proto.CompactTextString(m) }
func (*StrategyAddParam) ProtoMessage()    {}
func (*StrategyAddParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{5}
}

func (m *StrategyAddParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategyAddParam.Unmarshal(m, b)
}
func (m *StrategyAddParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategyAddParam.Marshal(b, m, deterministic)
}
func (m *StrategyAddParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategyAddParam.Merge(m, src)
}
func (m *StrategyAddParam) XXX_Size() int {
	return xxx_messageInfo_StrategyAddParam.Size(m)
}
func (m *StrategyAddParam) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategyAddParam.DiscardUnknown(m)
}

var xxx_messageInfo_StrategyAddParam proto.InternalMessageInfo

func (m *StrategyAddParam) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *StrategyAddParam) GetHandleMode() StrategyAddParam_HandleMode {
	if m != nil {
		return m.HandleMode
	}
	return StrategyAddParam_MODEDEFAULT
}

func (m *StrategyAddParam) GetDefenseType() StrategyAddParam_Type {
	if m != nil {
		return m.DefenseType
	}
	return StrategyAddParam_TYPEDEFAULT
}

func (m *StrategyAddParam) GetDIPList() []string {
	if m != nil {
		return m.DIPList
	}
	return nil
}

func (m *StrategyAddParam) GetURLList() []string {
	if m != nil {
		return m.URLList
	}
	return nil
}

func (m *StrategyAddParam) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

// 策略修改
type StrategySetParam struct {
	StrategyId           string                      `protobuf:"bytes,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	HandleMode           StrategySetParam_HandleMode `protobuf:"varint,2,opt,name=handle_mode,json=handleMode,proto3,enum=StrategySetParam_HandleMode" json:"handle_mode,omitempty"`
	Enable               bool                        `protobuf:"varint,7,opt,name=enable,proto3" json:"enable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *StrategySetParam) Reset()         { *m = StrategySetParam{} }
func (m *StrategySetParam) String() string { return proto.CompactTextString(m) }
func (*StrategySetParam) ProtoMessage()    {}
func (*StrategySetParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{6}
}

func (m *StrategySetParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrategySetParam.Unmarshal(m, b)
}
func (m *StrategySetParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrategySetParam.Marshal(b, m, deterministic)
}
func (m *StrategySetParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrategySetParam.Merge(m, src)
}
func (m *StrategySetParam) XXX_Size() int {
	return xxx_messageInfo_StrategySetParam.Size(m)
}
func (m *StrategySetParam) XXX_DiscardUnknown() {
	xxx_messageInfo_StrategySetParam.DiscardUnknown(m)
}

var xxx_messageInfo_StrategySetParam proto.InternalMessageInfo

func (m *StrategySetParam) GetStrategyId() string {
	if m != nil {
		return m.StrategyId
	}
	return ""
}

func (m *StrategySetParam) GetHandleMode() StrategySetParam_HandleMode {
	if m != nil {
		return m.HandleMode
	}
	return StrategySetParam_MODEDEFAULT
}

func (m *StrategySetParam) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

// 样本采集任务命令
type SampleSetParam struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CollectTimeRemain    uint32   `protobuf:"varint,2,opt,name=collect_time_remain,json=collectTimeRemain,proto3" json:"collect_time_remain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SampleSetParam) Reset()         { *m = SampleSetParam{} }
func (m *SampleSetParam) String() string { return proto.CompactTextString(m) }
func (*SampleSetParam) ProtoMessage()    {}
func (*SampleSetParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{7}
}

func (m *SampleSetParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleSetParam.Unmarshal(m, b)
}
func (m *SampleSetParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SampleSetParam.Marshal(b, m, deterministic)
}
func (m *SampleSetParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleSetParam.Merge(m, src)
}
func (m *SampleSetParam) XXX_Size() int {
	return xxx_messageInfo_SampleSetParam.Size(m)
}
func (m *SampleSetParam) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleSetParam.DiscardUnknown(m)
}

var xxx_messageInfo_SampleSetParam proto.InternalMessageInfo

func (m *SampleSetParam) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SampleSetParam) GetCollectTimeRemain() uint32 {
	if m != nil {
		return m.CollectTimeRemain
	}
	return 0
}

// 端口映射操作命令
type PortRedirectSetParam struct {
	SrcPort  string                        `protobuf:"bytes,1,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DestPort string                        `protobuf:"bytes,2,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Switch   bool                          `protobuf:"varint,3,opt,name=switch,proto3" json:"switch,omitempty"`
	Proto    PortRedirectSetParam_Protocol `protobuf:"varint,4,opt,name=proto,proto3,enum=PortRedirectSetParam_Protocol" json:"proto,omitempty"`
	// string id = 5;//端口映射规则ID
	DestIp               string   `protobuf:"bytes,6,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PortRedirectSetParam) Reset()         { *m = PortRedirectSetParam{} }
func (m *PortRedirectSetParam) String() string { return proto.CompactTextString(m) }
func (*PortRedirectSetParam) ProtoMessage()    {}
func (*PortRedirectSetParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{8}
}

func (m *PortRedirectSetParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PortRedirectSetParam.Unmarshal(m, b)
}
func (m *PortRedirectSetParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PortRedirectSetParam.Marshal(b, m, deterministic)
}
func (m *PortRedirectSetParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PortRedirectSetParam.Merge(m, src)
}
func (m *PortRedirectSetParam) XXX_Size() int {
	return xxx_messageInfo_PortRedirectSetParam.Size(m)
}
func (m *PortRedirectSetParam) XXX_DiscardUnknown() {
	xxx_messageInfo_PortRedirectSetParam.DiscardUnknown(m)
}

var xxx_messageInfo_PortRedirectSetParam proto.InternalMessageInfo

func (m *PortRedirectSetParam) GetSrcPort() string {
	if m != nil {
		return m.SrcPort
	}
	return ""
}

func (m *PortRedirectSetParam) GetDestPort() string {
	if m != nil {
		return m.DestPort
	}
	return ""
}

func (m *PortRedirectSetParam) GetSwitch() bool {
	if m != nil {
		return m.Switch
	}
	return false
}

func (m *PortRedirectSetParam) GetProto() PortRedirectSetParam_Protocol {
	if m != nil {
		return m.Proto
	}
	return PortRedirectSetParam_UNSET
}

func (m *PortRedirectSetParam) GetDestIp() string {
	if m != nil {
		return m.DestIp
	}
	return ""
}

type DeployerSetParam struct {
	DevName              string   `protobuf:"bytes,1,opt,name=dev_name,json=devName,proto3" json:"dev_name,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployerSetParam) Reset()         { *m = DeployerSetParam{} }
func (m *DeployerSetParam) String() string { return proto.CompactTextString(m) }
func (*DeployerSetParam) ProtoMessage()    {}
func (*DeployerSetParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_1bdf113f3d6e5a7a, []int{9}
}

func (m *DeployerSetParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployerSetParam.Unmarshal(m, b)
}
func (m *DeployerSetParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployerSetParam.Marshal(b, m, deterministic)
}
func (m *DeployerSetParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployerSetParam.Merge(m, src)
}
func (m *DeployerSetParam) XXX_Size() int {
	return xxx_messageInfo_DeployerSetParam.Size(m)
}
func (m *DeployerSetParam) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployerSetParam.DiscardUnknown(m)
}

var xxx_messageInfo_DeployerSetParam proto.InternalMessageInfo

func (m *DeployerSetParam) GetDevName() string {
	if m != nil {
		return m.DevName
	}
	return ""
}

func (m *DeployerSetParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeployerSetParam) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func init() {
	proto.RegisterEnum("Command_TaskType", Command_TaskType_name, Command_TaskType_value)
	proto.RegisterEnum("StatusUpdateParam_Type", StatusUpdateParam_Type_name, StatusUpdateParam_Type_value)
	proto.RegisterEnum("GwSetParam_Type", GwSetParam_Type_name, GwSetParam_Type_value)
	proto.RegisterEnum("DeviceSetParam_Type", DeviceSetParam_Type_name, DeviceSetParam_Type_value)
	proto.RegisterEnum("StrategyAddParam_Type", StrategyAddParam_Type_name, StrategyAddParam_Type_value)
	proto.RegisterEnum("StrategyAddParam_HandleMode", StrategyAddParam_HandleMode_name, StrategyAddParam_HandleMode_value)
	proto.RegisterEnum("StrategySetParam_HandleMode", StrategySetParam_HandleMode_name, StrategySetParam_HandleMode_value)
	proto.RegisterEnum("PortRedirectSetParam_Protocol", PortRedirectSetParam_Protocol_name, PortRedirectSetParam_Protocol_value)
	proto.RegisterType((*Command)(nil), "Command")
	proto.RegisterType((*FirmwareUpgradeParam)(nil), "FirmwareUpgradeParam")
	proto.RegisterType((*StatusUpdateParam)(nil), "StatusUpdateParam")
	proto.RegisterType((*GwSetParam)(nil), "GwSetParam")
	proto.RegisterType((*DeviceSetParam)(nil), "DeviceSetParam")
	proto.RegisterType((*StrategyAddParam)(nil), "StrategyAddParam")
	proto.RegisterType((*StrategySetParam)(nil), "StrategySetParam")
	proto.RegisterType((*SampleSetParam)(nil), "SampleSetParam")
	proto.RegisterType((*PortRedirectSetParam)(nil), "PortRedirectSetParam")
	proto.RegisterType((*DeployerSetParam)(nil), "DeployerSetParam")
}

func init() { proto.RegisterFile("scommand.proto", fileDescriptor_1bdf113f3d6e5a7a) }

var fileDescriptor_1bdf113f3d6e5a7a = []byte{
	// 1020 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xae, 0x9d, 0x2f, 0xe7, 0x6d, 0x1a, 0xa6, 0xb3, 0x55, 0x9b, 0x0a, 0x16, 0x2a, 0xc3, 0xa1,
	0x12, 0xc2, 0x42, 0x0b, 0x3d, 0x70, 0x00, 0xc9, 0xc4, 0xd3, 0xac, 0xb5, 0x69, 0x62, 0x8d, 0xc7,
	0x8d, 0x7a, 0xb2, 0x5c, 0xcf, 0xec, 0xd6, 0x22, 0x8e, 0x23, 0xdb, 0xdb, 0xaa, 0xfc, 0x23, 0x4e,
	0xfc, 0x06, 0x6e, 0x88, 0x3f, 0xc2, 0x85, 0x13, 0xbf, 0x00, 0xcd, 0xd8, 0x4e, 0x5a, 0x76, 0xab,
	0x3d, 0xec, 0xed, 0xfd, 0x78, 0xde, 0x77, 0x9e, 0xf7, 0x99, 0x2f, 0x18, 0x16, 0x71, 0x96, 0xa6,
	0xd1, 0x8a, 0x5b, 0xeb, 0x3c, 0x2b, 0x33, 0xf3, 0x37, 0x1d, 0x7a, 0xe3, 0x2a, 0x82, 0x2d, 0xe8,
	0x27, 0xa5, 0x48, 0xc3, 0xf2, 0x7e, 0x2d, 0x46, 0xda, 0x89, 0x76, 0x3a, 0x7c, 0xb1, 0x6f, 0xd5,
	0x49, 0x8b, 0x45, 0xc5, 0x2f, 0xec, 0x7e, 0x2d, 0xa8, 0x21, 0x31, 0xd2, 0xc2, 0x07, 0xd0, 0x59,
	0x47, 0x79, 0x94, 0x8e, 0xf4, 0x13, 0xed, 0x74, 0x40, 0x2b, 0x47, 0x46, 0xe3, 0x94, 0xbb, 0xce,
	0xa8, 0x75, 0xa2, 0x9d, 0xf6, 0x69, 0xe5, 0x98, 0x7f, 0x68, 0x60, 0x34, 0x2d, 0xf0, 0x01, 0x20,
	0x87, 0x9c, 0xdb, 0xc1, 0x94, 0x85, 0xcc, 0xf6, 0x5f, 0xb1, 0x2b, 0x8f, 0xa0, 0x1d, 0x0c, 0xd0,
	0x9d, 0x2c, 0x42, 0x9f, 0x30, 0xa4, 0xe1, 0x21, 0x80, 0x43, 0x2e, 0xdd, 0x31, 0x51, 0xbe, 0x8e,
	0x11, 0x0c, 0x7c, 0x46, 0x6d, 0x46, 0x26, 0x57, 0xa1, 0xed, 0x38, 0xa8, 0xf5, 0x28, 0x22, 0x31,
	0x6d, 0x59, 0xe3, 0xdb, 0x17, 0xde, 0xb4, 0xaa, 0xe9, 0xc8, 0x55, 0xbc, 0x39, 0x65, 0x94, 0x38,
	0x2e, 0x25, 0x63, 0xa6, 0xa2, 0x5d, 0xbc, 0x0f, 0x7b, 0x3e, 0xb3, 0x59, 0xe0, 0x87, 0x81, 0xe7,
	0xd8, 0x8c, 0xa0, 0x9e, 0x6c, 0xe5, 0x10, 0x6f, 0x3a, 0xbf, 0x22, 0x54, 0x81, 0x0c, 0x59, 0x7a,
	0xee, 0xd2, 0x8b, 0x85, 0x4d, 0x49, 0x18, 0x78, 0x13, 0x6a, 0x3b, 0x04, 0xf5, 0xcd, 0x7f, 0x34,
	0x38, 0x38, 0x4f, 0xf2, 0xf4, 0x2e, 0xca, 0x45, 0xb0, 0x7e, 0x93, 0x47, 0x5c, 0x78, 0x6a, 0xe4,
	0x11, 0xf4, 0x6e, 0x45, 0x5e, 0x24, 0xd9, 0x4a, 0xc9, 0xd6, 0xa7, 0x8d, 0x8b, 0x31, 0xb4, 0x8b,
	0xe4, 0x57, 0xa1, 0x14, 0x6a, 0x53, 0x65, 0x63, 0x04, 0xad, 0xb7, 0xf9, 0xb2, 0x96, 0x47, 0x9a,
	0xf8, 0x18, 0x0c, 0x7f, 0x3e, 0xae, 0x74, 0x6f, 0x57, 0x0d, 0xfc, 0xf9, 0x58, 0x49, 0xf5, 0x1c,
	0xe0, 0x3a, 0x8b, 0x72, 0x1e, 0xae, 0xa2, 0x54, 0x8c, 0x3a, 0x2a, 0xd9, 0x57, 0x91, 0x59, 0x94,
	0x0a, 0xfc, 0x25, 0xec, 0xbd, 0xae, 0x19, 0x55, 0xe5, 0x5d, 0x85, 0x18, 0x34, 0x41, 0xd5, 0xe3,
	0x21, 0x48, 0xb5, 0xe9, 0x3d, 0x06, 0xa9, 0x4e, 0x08, 0x5a, 0x29, 0x3f, 0x1b, 0x19, 0x15, 0xab,
	0x94, 0x9f, 0x99, 0xbf, 0x6b, 0xb0, 0xef, 0x97, 0x51, 0xf9, 0xb6, 0x08, 0xd6, 0x3c, 0x2a, 0xeb,
	0x59, 0xbf, 0x86, 0xf6, 0x83, 0xf3, 0x71, 0x64, 0xbd, 0x83, 0xb0, 0xd4, 0x29, 0x51, 0x20, 0x33,
	0x85, 0xb6, 0x62, 0xa0, 0x14, 0xae, 0x36, 0xdc, 0x9d, 0x9d, 0xcf, 0x9b, 0xcd, 0x56, 0xb6, 0x26,
	0xed, 0x6a, 0xb3, 0x91, 0x8e, 0xf7, 0xa0, 0x3f, 0x59, 0x78, 0x74, 0xce, 0xc8, 0x98, 0xa1, 0x16,
	0x1e, 0x80, 0xd1, 0xec, 0x32, 0x6a, 0xcb, 0x36, 0x0f, 0x77, 0x14, 0x75, 0x64, 0xbe, 0xd9, 0x3a,
	0xd4, 0x35, 0xef, 0x01, 0x26, 0x77, 0xbe, 0x28, 0x2b, 0xa6, 0x5f, 0x3d, 0x62, 0x8a, 0xac, 0x6d,
	0xea, 0x01, 0x45, 0x7c, 0x08, 0xdd, 0xe2, 0x2e, 0x29, 0xe3, 0x1b, 0xb5, 0x47, 0x06, 0xad, 0x3d,
	0xf3, 0x9b, 0x9a, 0xfa, 0x2e, 0xf4, 0x6a, 0xea, 0x68, 0x47, 0x3a, 0x0d, 0x37, 0x4d, 0x3a, 0x94,
	0xf8, 0xcc, 0xa6, 0x0c, 0xe9, 0xe6, 0x9f, 0x1a, 0x0c, 0x1d, 0x71, 0x9b, 0xc4, 0x62, 0xb3, 0xfe,
	0x73, 0x00, 0xae, 0x22, 0x61, 0x1a, 0xc5, 0xf5, 0xc1, 0xe8, 0x57, 0x91, 0x8b, 0x28, 0xc6, 0xa7,
	0x35, 0x3d, 0x5d, 0xd1, 0x3b, 0xb0, 0x1e, 0x57, 0xbf, 0x9f, 0x62, 0xeb, 0x11, 0xc5, 0xe0, 0x83,
	0x14, 0x07, 0x60, 0xb8, 0x33, 0x46, 0xe8, 0x4c, 0x5d, 0xa2, 0x23, 0x78, 0x36, 0x09, 0x88, 0xcf,
	0x42, 0x7b, 0x3c, 0x26, 0xbe, 0x1f, 0xd6, 0xa2, 0x2b, 0x95, 0xa7, 0xf6, 0xec, 0xd2, 0xf5, 0x5d,
	0x86, 0xda, 0xe6, 0xbf, 0x3a, 0x20, 0xbf, 0xcc, 0xa3, 0x52, 0xbc, 0xb9, 0xb7, 0x39, 0xaf, 0x86,
	0xf9, 0x02, 0x76, 0x8b, 0x3a, 0x16, 0x26, 0xbc, 0x9e, 0x06, 0x9a, 0x90, 0xcb, 0xf1, 0x8f, 0xb0,
	0x7b, 0x13, 0xad, 0xf8, 0x52, 0x84, 0x69, 0xc6, 0x9b, 0xa9, 0x3e, 0xb3, 0xfe, 0xdf, 0xc8, 0x7a,
	0xa9, 0x40, 0x17, 0x19, 0x17, 0x14, 0x6e, 0x36, 0x36, 0xfe, 0x01, 0x06, 0x5c, 0xbc, 0x16, 0xab,
	0xa2, 0x3e, 0xc7, 0x2d, 0x55, 0x7f, 0xf8, 0x6e, 0xbd, 0xd2, 0x65, 0xb7, 0xc6, 0xaa, 0xf1, 0x8f,
	0xc1, 0xe0, 0xae, 0x17, 0x2e, 0x93, 0xa2, 0x1c, 0x75, 0x4e, 0x5a, 0xf2, 0xf6, 0x70, 0xd7, 0x9b,
	0x26, 0x45, 0x29, 0x53, 0x01, 0x9d, 0x56, 0xa9, 0x6e, 0x95, 0x0a, 0xe8, 0x54, 0xa5, 0x0e, 0xa1,
	0x2b, 0x56, 0xd1, 0xf5, 0xb2, 0xba, 0x0d, 0x06, 0xad, 0x3d, 0xf3, 0xac, 0x16, 0xf5, 0x13, 0xd8,
	0x95, 0xef, 0xd2, 0x56, 0xd8, 0x3d, 0xe8, 0x2f, 0x5e, 0xba, 0x8c, 0x5c, 0xcc, 0x1d, 0x82, 0x34,
	0xe9, 0xfe, 0x3c, 0xb5, 0xc7, 0xaf, 0x94, 0xab, 0x9b, 0x3f, 0x01, 0x6c, 0x27, 0x93, 0xc5, 0x32,
	0xbe, 0x2d, 0xc6, 0x30, 0xf4, 0x28, 0xb9, 0x24, 0x33, 0xb6, 0xb0, 0xe9, 0xcc, 0x9d, 0x4d, 0xaa,
	0xf3, 0xd3, 0x38, 0xba, 0xf9, 0x97, 0xb6, 0x15, 0x7d, 0x73, 0x82, 0x3e, 0x56, 0xf4, 0xcd, 0x61,
	0x7a, 0x42, 0xf4, 0xa7, 0x34, 0xf8, 0xd8, 0x61, 0x3c, 0x18, 0xfa, 0x51, 0xba, 0x5e, 0x6e, 0xef,
	0xc2, 0x10, 0xf4, 0xcd, 0x00, 0x7a, 0x22, 0xbf, 0x9a, 0x67, 0x71, 0xb6, 0x5c, 0x8a, 0xb8, 0x0c,
	0xcb, 0x24, 0x15, 0x61, 0x2e, 0xd2, 0x28, 0x59, 0xa9, 0x01, 0xf6, 0xe8, 0x7e, 0x9d, 0x62, 0x49,
	0x2a, 0xa8, 0x4a, 0x98, 0x7f, 0x6b, 0x70, 0xe0, 0x65, 0x79, 0x49, 0x05, 0x4f, 0x72, 0x11, 0x97,
	0x9b, 0xc6, 0xc7, 0x60, 0x14, 0x79, 0x1c, 0xae, 0xb3, 0xbc, 0x6c, 0xde, 0xde, 0x22, 0x8f, 0x25,
	0x14, 0x7f, 0x0a, 0x7d, 0x2e, 0x8a, 0xb2, 0xca, 0xe9, 0x2a, 0x67, 0xc8, 0x80, 0x4a, 0x3e, 0x71,
	0xa7, 0xf0, 0xf7, 0xd0, 0x51, 0x1f, 0xa3, 0x7a, 0x87, 0x87, 0x2f, 0x3e, 0xb7, 0xde, 0xb7, 0xaa,
	0xe5, 0x49, 0x48, 0x9c, 0x2d, 0x69, 0x05, 0xc6, 0x47, 0xd0, 0x53, 0x4b, 0x25, 0xeb, 0xfa, 0x01,
	0xee, 0x4a, 0xd7, 0x5d, 0x9b, 0xdf, 0x82, 0xd1, 0x60, 0x71, 0x1f, 0x3a, 0xc1, 0x4c, 0xfe, 0x2f,
	0x3b, 0xb8, 0x07, 0xad, 0xc0, 0xf1, 0x90, 0x26, 0x0d, 0x36, 0xf6, 0x90, 0x2e, 0x0d, 0x7b, 0x3a,
	0x45, 0x2d, 0x73, 0x01, 0xc8, 0x11, 0xeb, 0x65, 0x76, 0x2f, 0xf2, 0x87, 0x43, 0x72, 0x71, 0x5b,
	0xbd, 0xdd, 0xf5, 0x90, 0x5c, 0xdc, 0xaa, 0x67, 0x1b, 0x43, 0x5b, 0x85, 0xab, 0xf9, 0x94, 0xad,
	0xfe, 0xe5, 0x9b, 0x6c, 0x25, 0x9a, 0x1f, 0x58, 0x39, 0xd7, 0x5d, 0x45, 0xf5, 0xbb, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xb2, 0x43, 0xa5, 0x28, 0x02, 0x08, 0x00, 0x00,
}
